### ISSUE TITLE
As an admin, I want to upload files and media and associate them with other content so that I can share files and other non-web content with users.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#10]
## Notes for testing
- Attachments should now be included in the top level content menu in the admin.
- Attachments can be edited there _or_ on each of the other individual items (rich text page, landing page, project, event, profile, blog post).  Please test both ways.
- A single attachment can be associated with multiple different pages or kinds of content.

**Comment by rgmunson** [comment]
Attachments are in the top-level content menu and can be edited there or in individual items. I was able to edit both ways. I added an attachment on the top-level and was able to change its associations. I was also able to remove or add from a project page. I associated the file I uploaded (the bitKlavier charter) with both its project page and my profile and it appeared both times. 

One thing to note is that if you associate a file with a page (I did "Research/Projects") and then add a project-attachment relationship two copies of the file, both available for download, will appear on the project page. I'm not sure if this is a bug or not so I'm flagging it with a question.
