### ISSUE TITLE
Hard to differentiate bold text 

### ISSUE THREAD

**Issue by dschlein** [Princeton-CDH/cdh-web#100]
When making the text bold in the editor, it's hard to tell that any text has been boldened, both in the editor and on the site. My browser is google chrome, Version 65.0.3325.181.
The first screenshot is from the editor.
![screen shot 2018-04-18 at 11 00 15 am](https://user-images.githubusercontent.com/38290394/38940303-ccaf015e-42f7-11e8-9dbe-b94b9962d39c.png)
The second screenshot is from the website.
![screen shot 2018-04-18 at 11 00 44 am](https://user-images.githubusercontent.com/38290394/38940311-ce8c12aa-42f7-11e8-9658-ba06dd304f7c.png)

**Comment by thatbudakguy** [comment]
The difference is very apparent now in all browsers and in the editor, perhaps because of the font-smoothing or changes applied to address #93 .
