### ISSUE TITLE
HTML entity rendering issues

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#102]
## testing notes
- the short descriptions of blog posts that are displayed on the blogpost archive page should show characters like typographic quotes (“”) correctly. there shouldn't be any `&ldquo;`, `&nbsp;`, etc.
- you can test this by looking at the "hiring a graphic designer" post in the list on the test site [here](https://test-web.cdh.princeton.edu/updates/). it should show the quotes correctly, vs the version of the post in the list on the production site [here](https://cdh.princeton.edu/updates/) which has the `&ldquo;`, etc.
- this also occurs when the post is showed on the homepage featured post "carousel" (the big display). if you find the "hiring a graphic designer" post on the homepage, you should see that the quotes also render correctly in its description there (no `&ldquo;`).

## dev notes
text saved as part of blog posts is displaying without converting HTML entities, e.g. typographic quotes.

![screen shot 2018-04-18 at 1 22 42 pm](https://user-images.githubusercontent.com/4924494/38947705-9adc227e-430b-11e8-8656-7ca273ccc3ef.png)

potentially due to the way that mezzanine stores text at rest. this is currently visible on carousel slide number 2 on the test site.

**Comment by norabenedict** [comment]
Checked both versions of the blog post on both linked sites and everything displays correctly.
