### ISSUE TITLE
home page carousel doesn't respect draft status

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#103]
## testing notes
- visit the [admin interface](https://test-web.cdh.princeton.edu/admin/blog/blogpost/) for blogs, and select any blog post.
- check the "featured" box:
![screen shot 2018-08-30 at 1 53 03 pm](https://user-images.githubusercontent.com/4924494/44869644-18551d00-ac5c-11e8-9ec3-17671cc95d70.png)
- make sure that the post is set to "draft" status (not published):
![screen shot 2018-08-30 at 1 54 21 pm](https://user-images.githubusercontent.com/4924494/44869699-3d499000-ac5c-11e8-9075-932c4de7330d.png)
- save the post, visit the home page, and confirm that the post *does not* appear in the featured post carousel (the large display at the top of the page).
- go back to the admin interface and change the status to "published" for the post.
- save the post, visit the home page, and confirm that the post *does* now appear in the featured post carousel.

**Comment by norabenedict** [comment]
Everything works well with the instructions. No problems or bugs.
