### ISSUE TITLE
wysiwyg editor style issues

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#104]
Some issues with wysywig editor:

- admin site styles are affected (does not seem to be happening on the test site)
- some of the inputs and dialog boxes are hard/impossible to use, likely due to styles affecting the admin page and not just the wysiwyg edit form
- images with height/width don't display properly when published (we don't actually want people to add image sizes, but how best to handle? confusion caused by images not displaying properly in preview)
- check Xinyi's style guide for minimum blank space beneath image caption so that it does not run up against subsequent text (see screenshot) 
- it's difficult to work in the wysywig editor/add a caption once you add a very large image because the image "takes over" the editor and you cannot see the entire image at once. Is there a way to limit the size that the image appears in the editor? 
- can't add a COinS, e.g. from Zotero bibliography (probably because empty span is being stripped out?)

<img width="717" alt="screen shot 2018-07-02 at 12 34 01 pm" src="https://user-images.githubusercontent.com/22945600/42175798-c123b4c8-7df4-11e8-8b0a-1c31e2c2e211.png">

**Comment by thatbudakguy** [comment]
resolved by switching to wagtail as WYSIWYG editor is no longer used
