### ISSUE TITLE
images smaller than content width are not centered

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#105]
<img width="731" alt="screen shot 2018-07-02 at 12 18 43 pm" src="https://user-images.githubusercontent.com/691231/42175012-1cf4fd64-7df2-11e8-98a1-cec1c458a465.png">

**Comment by rlskoeser** [comment]
I think this is fixed, @thatbudakguy would you review?

**Comment by thatbudakguy** [comment]
Is there a particular post that exemplifies this? the ones in QA look like the images are all sized to fit the width of the post. Does that mean it's working?

**Comment by rlskoeser** [comment]
@thatbudakguy I don't know of any current examples - it came up when Mary was working on the PPA post she did after DH2018, but I think we worked around it. You can either set the size smaller manually or add/upload a small image to check.

**Comment by thatbudakguy** [comment]
Uploaded a small image to check and it was correctly centered! 🌮
