### ISSUE TITLE
As a user, I want to see CDH staff, postdocs, and students on separate pages so I can see current and past people associated with CDH grouped by category.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#108]
## Notes for testing
- Go to people/staff page and use right-side drop-down navigation to navigate to other pages (ignore top-level navigation, will be handled separately).
- Main staff page should show current and past staff in two different sections on the same page, and should not include postdocs and students.
- There should be a separate page for postdocs with sections for current and past postdocs.
- There should be a separate page for students with sections for current and past student staff and student affiliates. Should include students who have worked for us and _also_ those who have had grants with us.  Past students should display dates they worked for us or dates for their grant. For a grantee to be displayed on this page, they need to have a profile with Princeton status set to graduate or undergraduate, profile should be published, and be a project director on a grant. I've updated one record so it will shop up but feel to tinker with it or edit others.  

## Notes for development
- break current people page out as follows:
   - staff
   - post-docs 
   - students = grant recipients or CDH role
- display current and past people on the same page in two sections (similar to current/past events) instead of a separate alumni page

**Comment by norabenedict** [comment]
Everything works great with these features! 

For design, I wonder if it would be possible to change the drop down display to "Filter" or "Categories" rather than "Staff," which is in and of itself one of the categories?
