### ISSUE TITLE
As a user, I want to see upcoming and past speakers at CDH events so I can see what kind of scholars CDH is bringing to campus.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#109]
## testing notes

_n.b._
there isn't currently a navigation link to this page, so you'll need to access it by typing or pasting into the URL bar:

<https://test-web.cdh.princeton.edu/people/speakers/>

being a "speaker" for the purposes of the website relies on a few things:
- you have a profile on the website
- your profile is published (not a draft)
- your profile has the "external" status (i.e. not affiliated with princeton)
- the user account associated with your profile is also associated with at least one event
- that event is also published

### to test this...
- go to the [admin backend for profiles](https://test-web.cdh.princeton.edu/admin/people/profile/) and find your profile and edit it (or anyone's; shouldn't matter for testing purposes).
- below "title", set your princeton status to "not associated with princeton". also set your "institution" to whatever you want (this will be displayed on the speakers list with your profile).
- make sure your status is set to "published" and save the profile.
- go to the [admin backend for events](https://test-web.cdh.princeton.edu/admin/events/event/) and create a new event
- fill out the required fields (title, start/end time, type) and use the menu system to add yourself as a speaker for the event. make sure to have the event start and end in the future. save the event.
- now go to the [speakers page](https://test-web.cdh.princeton.edu/people/speakers/) and check the list of "upcoming speakers" to see if your profile appears.
- your name, your institutional affiliation, and the start time of your new event should be displayed in the list.
- there should also be a calendar icon just above your profile picture that will take you to the new event listing you created.
- now go back to the [admin backend for events](https://test-web.cdh.princeton.edu/admin/events/event/) and find the event you created previously.
- edit the start and end time so that they're both in the past.
- return to the [speakers page](https://test-web.cdh.princeton.edu/people/speakers/) and check the list of "past speakers" to see if your profile appears.
- the year of your past event should be shown.

## Notes for development
- new speakers page (based on staff page)
- add fields to track institution, department
- display name, photo, institution, department, title
- display associated event(s) and date
- profile card should link to external website / profile
- order by event date (upcoming/most recent first)

**Comment by thatbudakguy** [comment]
filters:
- has PU status `external`
- has at least one event

show on upcoming card:
- day/month of soonest upcoming event
- speaker's title (depends on #107 ) for title info
- name

show on past card:
- unique years of past events (not a range but a list)
- speaker's title
- name

**Comment by norabenedict** [comment]
While there aren't any (past or present) speakers listed on the page, it works fine to navigate from the Staff page and then sort in the drop-down for speakers. 

My only concern with this location/filtering method is that I don't mentally affiliate "(guest) speakers" with "staff" and would not know to look her for their information. Perhaps it would make more sense to include these information pages under "community" or just create a separate tab in the "about" drop-down for "(guest) speakers".

**Comment by norabenedict** [comment]
Tested all of the speaker features. The profile features all work (not affiliated with Princeton, guest speaker, etc.), and when published, the future event(s) display correctly. The only slight glitch pertains to past events. When you change an event to the past, the display of dates, etc., is correct, but if there is a future event with this speaker (in draft form), the speaker's profile still remains under the heading of "future speakers".

**Comment by rlskoeser** [comment]
Checked the same page & data with the latest code and it now displays correctly. 🎉
