### ISSUE TITLE
As a user, I want to easily find project URLs so I can get to the actual websites and see projects that are live.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#112]
## Notes for testing
On the project detail page, resource links (website, github, twitter) should now be at the top of the left side instead of the bottom. They should have icons, and the project website url should also be displayed under the title.

## Notes for development
- make website link more prominent on project detail page 
- include website link on project list page

**Comment by dschlein** [comment]
The website url and github links are easy to find at the top of the project detail pages. I didn't see any pages with twitter links at the top, though. I was able to discern which projects had these links by the CDH arrow on the project card (which navigates from the projects list page to the project detail page). Out of curiosity, are the CDH arrow badges above the project cards more for internal CDH staff benefit then for the benefit of the website visitors? I'm not sure that's intuitive for an average website visitor.
