### ISSUE TITLE
As a user, I want to see which projects were developed by CDH so that I can get a better sense of CDH involvement in the projects.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#114]
## Notes for testing
- When editing projects in the admin, there is now a checkbox to indicate a project was "built by CDH"
- On the project list view, projects that are marked as "built by CDH" in the admin should have a little badge above the project card showing that they are built by CDH

## Notes for development
- add a new database flag to project
- display a badge over the project card with text "built by CDH"; use style from event card event type
- ~update home page featured projects to filter to projects built by CDH~

**Comment by dschlein** [comment]
The checkbox that indicates the project was built by the CDH is there on the project editing page. You can view the projects "built by CDH" using the filter on the right hand side of the projects list page. On the CDH website, the badge for projects "built by CDH" appears on the top left of the project card.
