### ISSUE TITLE
As a user, I want to see which projects in the project list have a live website so that I can see which projects are accessible and get to them.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#115]
## Notes for testing
- projects on the project list that have an associated website should have a link icon above the project card
- clicking on the link icon should take you to the project website

## Notes for development
- use small version of link icon above project card to indicate project is live (and link to project)
- base on website url in db

**Comment by dschlein** [comment]
The link icon above the project card is fairly easy to spot and a nice size, and clicking on the link icon takes me directly to the project website. I do still wonder if that's completely intuitive, though. When you mouse over the link icon, you can tell it should take you some place (the pointer hand appears), but I wouldn't have known that if I'd just gone looking for project data - i.e. I would have clicked on the card directly, and then found the website link on the project details page. I wonder, then, how impactful the link icon above the project cards would be to begin with.
