### ISSUE TITLE
As a content admin, I want to document event attendance in the database so that it can be tracked and reported with other event information.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#116]
## Notes for testing
- When editing an event in the admin, there's now a field where you can record total attendance at an event.
- Attendance should be optional; check that you can still save an event without a number

## Notes for development
- add attendance field
- make editable in admin (not for public display)

**Comment by dschlein** [comment]
I checked the edit pages for past and future events on the admin CDH site, and I couldn't find the attendance field. So it doesn't appear to be showing up yet.
