### ISSUE TITLE
As a user, I want to see the pages associated with the page I'm viewing so I can easily navigate to related content.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#119]
## Notes for testing
- Pages that have associated pages under them in the navigation hierarchy should now display a card at the bottom of the page for each related subpage.  Test that landing pages (top-level sections) display cards for each of the pages under them, and test second-level pages with subsections (currently only Grants) also show cards. 
- Pages should display in the order they are set in the admin; try re-ordering something in the admin and reloading to check. 
- Pages should only show if they have the "show on parent page as attachment card" option checked under the show in menus. Try changing this for a page and check the display on the parent page.

## dev notes

- [x] edit `PAGE_MENU_TEMPLATES` in `settings.py`, replacing "left-hand tree" with this new snippet
- [x] create the new snippet that will be rendered at the bottom of main content
- [x] get the set of child pages and render them as attachment cards
- [x] only render children that are `page.in_menu`
- [x] mezzanine checkbox should read "show on parent page as attachment card"

**Comment by jimccasey1** [comment]
Logged into the new site and all looks good. Cards at the bottom of the page are really cool!

-(yes) Pages that have associated pages under them in the navigation hierarchy should now display a card at the bottom of the page for each related subpage. Test that landing pages (top-level sections) display cards for each of the pages under them, and test second-level pages with subsections (currently only Grants) also show cards.
-(yes) Pages should display in the order they are set in the admin; try re-ordering something in the admin and reloading to check.
-(yes) Pages should only show if they have the "show on parent page as attachment card" option checked under the show in menus. Try changing this for a page and check the display on the parent page.
