### ISSUE TITLE
As an admin user, I want to create and edit project pages so that I can publish information about sponsored projects.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#12]
## Notes for testing
- test grant type and associating grants with projects via #33 
- test editing project roles and associating contributors with projects via #34 

---

As an admin user, I want to be able to create and edit project information, so that I can inform the Princeton community and public about  contributions to DH projects. These include:

- [x] Setting a large image
- [x] Thumbnail image
- [x] tagline
- [x] Project contributors (linked to people in the site's database)
- [x] Project contributor roles
- [x] Paragraph text

**Comment by rgmunson** [comment]
Might be helpful to pre-populate the roles list as well as the "project resources" (which we're going to make a separate user story).
