### ISSUE TITLE
As an admin, I want to edit text content on the home page so that I can manage and update brief introductory content for site visitors.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#123]
## Notes for testing
- There is now a special page called 'Home' in the admin Pages list. I created it, because it has to be set up a particular way. When you edit the page content, you should see that reflected on the home page. 
- HTML title and description are now generated from the editable page when it is available. Feel free to edit them in the metadata section. 
- If you delete the 'Home' page in admin, the home page should display normally without the text content.

**Comment by norabenedict** [comment]
Everything works accordingly with the new "Home" page.
