### ISSUE TITLE
As a content admin, I want to add and edit text to be included on people pages so that I can describe faculty affiliation or other groups.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#132]
## Notes for testing
If a mezzanine page matches the url for a dynamic people list page, the text content will be displayed. I've created one on the test site for the faculty affiliates. Test that editing it in the admin displays updated text on the dynamic page; removing it shouldn't cause an error (no text will be displayed). Adding a new page with an appropriate url (e.g. `/people/staff/`) should cause page content to be added to the corresponding people page.

**Comment by norabenedict** [comment]
Changed the content for the page and it updated correctly. Changed the url to ```/people/staff``` and it changed to content accordingly. All in working order.
