### ISSUE TITLE
Investigate pa11y-ci timeout on travis-ci

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#134]
pa11y-ci times out on travis-ci, even though the django requests (including assets) succeed. As a work around, testsettings have been configured with `DEBUG = True`. Seems to be a django-compressor problem; it looked like setting `COMPRESS_ENABLED` to `False` ought to circumvent the problem, but that didn't fix the issue on travis either.

May require further troubleshooting in a local docker image - see https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image

**Comment by thatbudakguy** [comment]
closing in favor of #198
