### ISSUE TITLE
Speakers should be ordered by event date

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#139]
## testing notes
(for speakers that appear on the [speakers list page](https://test-web.cdh.princeton.edu/people/speakers/))

- upcoming speakers should be sorted so that the speaker whose event is happening soonest is first
- past speakers should be sorted so that those who had an event latest/most recent year are first
- events that aren't published shouldn't affect the order of the speakers (you can test by giving a person two events with different dates and only publishing one of the events)

**Comment by rlskoeser** [comment]
Just verified, this corrects the problem exposed by the actual data on the test site.
