### ISSUE TITLE
As a content editor, I want to create and edit events so that I can publicize workshops, lectures, or other events.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#14]
## Notes for testing
- test event types management separately - #37 
- test event locations management separately - #38 

---- 

These events need to capture:
- [x] title
- [x] location
- [x] schedule / time
- [x] description of event
- [x] large image
- [x] thumbnail photo

**Comment by rgmunson** [comment]
I created an event for today's user testing session that incorporated the checklist features. I learned that I'm not good at resizing thumbnails but otherwise everything displays perfectly.
