### ISSUE TITLE
blog post list links author names to non-existent profiles

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#141]
See Florent's post on bitKlavier for an example. Should use the new `profile_url` property that's now used on project detail pages (links to published profile _or_ external website)

**Comment by rlskoeser** [comment]
Also applies to event detail page.

**Comment by bwhicks** [comment]
I tested this using Alex's non profile. It is correctly not linked in the blog list (although none of them are linked in the blog post detail view, so I assume that is deliberate)
