### ISSUE TITLE
As a user, I want to view content pages so that I can read materials that interest me.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#15]
## Notes for testing
Styles for generic content pages have been improved.  Should be easier to test this with content imported from production site.

**Comment by rlskoeser** [comment]
Splitting out #28 because I think that will require separate, more extensive testing.

**Comment by rlskoeser** [comment]
General content page template/styles haven't been customized yet, so I think it's better to hold off on testing this one.

**Comment by rgmunson** [comment]
I ran through the content pages for all our major categories and, first, they're beautiful and second, I didn't see any trouble with displaying any of the content. The styles on "updates" and "events" are slightly different than the other content landing pages but I assume that's the design so all looks good here!
