### ISSUE TITLE
As a content editor, I want to search for people by name when adding them to projects, events, or setting tem as blog post authors, so that I can easily lookup the correct person.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#150]
Probably an autocomplete field would be nice. In some cases, it's just a drop down listed in the order that people were added to the database, which is not very useful.

**Comment by rlskoeser** [comment]
@cvansant I've integrated a wagtail autocomplete package and enabled it for Person lookup. Please try it out in the following places:
- project edit page, add/edit project team members
- events edit page, add/edit speakers
- blog post, add/edit authors

Please LMK if there's anywhere else we add people that I missed. And if this functionality is applicable to other lookups, let me know — it was pretty easy to integrate it.

**Comment by cvansant** [comment]
It's a little hard to read the options other than the top one but it works!
![Screen Shot 2023-08-14 at 8 09 29 PM](https://github.com/Princeton-CDH/cdh-web/assets/60949427/d3c3c082-9c4b-44d2-80c1-fac4bfe565e0)

**Comment by rlskoeser** [comment]
reopening to address styling problem

**Comment by rlskoeser** [comment]
@cvansant I tweaked the styles so that unselected terms are readable, please confirm.

**Comment by cvansant** [comment]
@rlskoeser Works perfectly! If you're ever bored, it would be great to do the same with "titles," which is under "positions" on each person's page. We have a lot of titles now so autocomplete would be nice.

![Screen Shot 2023-08-28 at 11 15 49 PM](https://github.com/Princeton-CDH/cdh-web/assets/60949427/a03110dc-7718-4ac5-ae96-8eac0603e6d1)

**Comment by rlskoeser** [comment]
@cvansant boredom unlikely but I did want to know where else we need this functionality, so thank you. The other one I noticed is membership positions on the project page. I'll make an issue. Let me know if you think of others.
