### ISSUE TITLE
Event card doesn't display names from person, only from profile

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#153]
# testing notes
n.b. this fix was already manually added in production, so there are no actual instances of the bug that you can view IRL anymore - we just need to test it a slightly different way.

1. [create a new event](https://test-web.cdh.princeton.edu/admin/events/event/add/) on the test site
2. fill in any random details you want - just make sure there's a title and type, it's set to "published", and it has a start/end date sometime **in the future**
3. choose any person you want from the list to be a speaker and add them to the event.
4. go to the [event list page](https://test-web.cdh.princeton.edu/events/) and confirm that the card preview for your event appears, and that the speaker name is correct.
5. click the card for your event to go to its detail page, and confirm again that the speaker's name is listed to the left and it's the same one that showed on the list page.
6. go to the [list of profiles](https://test-web.cdh.princeton.edu/admin/people/profile/) and edit the profile of whoever you added as a speaker to your event in step 3.
7. change the profile's title (person's name) to something different (doesn't matter what). remember this is the test site, so you can write whatever you want.
8. repeat steps 4 and 5, confirming that the name that displays on the event card and on its detail page are the **new name** that you just edited in the profile (and that they're consistent).

# dev notes
Should just use `person` (string method) instead of `person.profile.title`

**Comment by rgmunson** [comment]
Sorry, guys, looks like this bug is still operational. I created an event ("Margarita Slip n Slide") and assigned it to Jim (naturally) and it showed up just fine. I went in and changed Jim's name ("Jim Casey, Guru") and the change was reflected on the events list page but NOT on the detail page. That remained the same as it was initially, robbing Jim of his guru status.

**Comment by rgmunson** [comment]
Ok - turns out I forgot my testing practices and didn't do a hard refresh so it was just the cached version. All good!
