### ISSUE TITLE
Links in lists don't get body link style

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#154]
<img width="693" alt="screen shot 2019-02-05 at 12 18 30 pm" src="https://user-images.githubusercontent.com/691231/52292278-5dcff180-2942-11e9-804f-3033d0ae7a92.png">

**Comment by rlskoeser** [comment]
Also links in headers
![Screen Shot 2019-05-08 at 5 22 54 PM](https://user-images.githubusercontent.com/691231/57409331-0564f600-71b6-11e9-9494-9d19a9e9825b.png)

**Comment by thatbudakguy** [comment]
it looks like this is specific to updates. it works correctly on these pages:

- [an event](https://cdh.princeton.edu/events/2019/04/building-bridges-data/)
- [a page](https://cdh.princeton.edu/grants/external-funding-opportunities/)

but not on [this post](https://cdh.princeton.edu/updates/2019/06/05/look-back-cdhs-year-data-photos/).

**Comment by thatbudakguy** [comment]
looks like this is working correctly on some posts in qa:
- https://test-web.cdh.princeton.edu/updates/2018/09/12/cdh-reading-group-collections-data/
- https://test-web.cdh.princeton.edu/updates/2018/07/23/cdh-hiring-graphic-designer/
