### ISSUE TITLE
As a Content Editor, I want to add text content to the events page so that I can add context to the list of events.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#159]
moved from [asana task](https://app.asana.com/0/1134940917892680/1135800187094943/f)

should this text be optional?

**Comment by thatbudakguy** [comment]
tested in qa and was able to insert a blurb above the events area:
https://test-web.cdh.princeton.edu/events/

**Comment by thatbudakguy** [comment]
...but it probably needs to be optional, and it isn't right now.

**Comment by thatbudakguy** [comment]
so we can't make the text optional, but we can detect in the template if it's only whitespace and not render the section if so. we need to do this on the events list page as well as profile list pages.

**Comment by rlskoeser** [comment]
The only thing I could figure out was to check explicitly for two non-breaking spaces (which is the minimum I was able to get mezzanine to allow me to save before). Hopefully this is good enough for now.

**Comment by thatbudakguy** [comment]
closing since @rlskoeser got this to work in QA; despite my inability to type a non-breaking space.
