### ISSUE TITLE
adjust content priority values in sitemap

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#160]
we appear to be using boosting values to alter the priority of content in mezzanine's generated sitemap, but it's not clear what is driving the values or if they reflect our desired SEO strategy.

**Comment by thatbudakguy** [comment]
# priority breakdown
default priority is `None`, which I think is evaluated as **0.5**, but doesn't appear in the sitemap xml.
## projects
- base project: **0.5**
- project with a website: **0.6**
- cdh-built project: **0.6**
- cdh-built project with website: **0.7**
https://github.com/Princeton-CDH/cdh-web/blob/03a0f2779ef1a60917af81246e554299eb708b8e/cdhweb/projects/sitemaps.py#L5-L17
## pages
- base page: **0.5**
- landing page: **0.6**
https://github.com/Princeton-CDH/cdh-web/blob/03a0f2779ef1a60917af81246e554299eb708b8e/cdhweb/resources/sitemaps.py#L22-L36

**Comment by rlskoeser** [comment]
I think it's part of the sitemap spec, if you don't specify a priority it defaults to 0.5.

Projects could potentially have an additional boost if they are featured, but featured projects probably overlaps pretty well with built by cdh & has a website.

I wonder if our landing pages actually should be higher priority? They aren't really that content-rich. It's probably the secondary pages that are more significant (but I don't know if that's true across the board).

I would like to boost the priority of the blog posts / updates - but I'm not sure how much or if we should do it across the board. I think some are more important / have more lasting significance than others, but I don't think we have a programmatic way to do that. Maybe we could key on the featured flag, which would prioritize recent high-priority content.

**Comment by thatbudakguy** [comment]
Agree that landing pages don't necessarily deserve boosting.

Keying on the featured flag also seems like a sound idea to me. Should we start small and just give featured updates a **0.6**?

**Comment by rlskoeser** [comment]
That sounds reasonable to me. And drop the landing page boosts, probably.

**Comment by thatbudakguy** [comment]
tested in qa and seem to be getting the right output for featured posts:
```
  <url>
    <loc>https://test-web.cdh.princeton.edu/updates/2018/11/15/test/</loc>
    <lastmod>2019-06-06</lastmod>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://test-web.cdh.princeton.edu/updates/2018/09/12/cdh-kicks-year-data/</loc>
    <lastmod>2019-08-29</lastmod>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://test-web.cdh.princeton.edu/updates/2018/09/12/cdh-reading-group-collections-data/</loc>
    <lastmod>2019-08-29</lastmod>
    <priority>0.6</priority>
  </url>
```
