### ISSUE TITLE
second-level nav items don't respect "show in nav" checkbox

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#162]
editing a page in the second-level nav (try any of the grants) and unchecking the "show in top nav" checkbox does _not_ remove it from the navigation menu. it will appear unless moved out of the hierarchy in the mezzanine pages menu.

**Comment by thatbudakguy** [comment]
this doesn't appear to be working for me in qa. unchecked "show in top navigation bar" for the public humanities seed grants page but it's still there.

**Comment by rlskoeser** [comment]
Not working for me either. I wondered if maybe mezzanine was caching something, but I moved the page and that update showed.

**Comment by rlskoeser** [comment]
The mezzanine page menus tag logic is based on settings and template name, so it doesn't work properly for the secondary and tertiary nav (unless we wanted to add additional checkboxes for them, which seems much more complicated).  I added explicit checks for the page menus option we care about in the secondary and tertiary nav templates.

**Comment by thatbudakguy** [comment]
tested by checking/unchecking the "show in nav" box on the public humanities seed grants page (which is nested under engagement/grants) and it works as expected.
