### ISSUE TITLE
add text-shadow to landing page headings

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#166]
john jameson recommended:
```css
 text-shadow: 0 0 55px rgba(0, 0, 0, 0.5); 
```
we are looking to create this type of effect, to maximize contrast:
![image005](https://user-images.githubusercontent.com/4924494/63453781-6cca4d00-c417-11e9-8a88-368178efcda2.png)

**Comment by rlskoeser** [comment]
This looks good. Not super noticeable on the images (which is nice), but I confirmed it was there by editing the DOM to hide the landing page background images. It does seem like the text is more readable now.
