### ISSUE TITLE
As a user I want to view upcoming events and highlighted projects on the homepage so I can get a sense of the CDH and its activities.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#17]
## Notes for testing
- update 9/21: I think the image display issue was a media/deploy problem that's been resolved, please retest
- displays next three upcoming events. 
- displays 4 random projects that are ~_current_ (i.e. has a grant that is active now based on the dates) and _active_~ marked as _highlighted_
- only displays events and projects that are published ~(but logged in admins will see draft content even though we don't yet have a marker for draft content)~
### updates for re-testing 9/5
- "upcoming" events now includes events starting any time on the current day, even if it is already started.  Please test with events before today, current day, and future.
- Discussed project logic with Jean and renamed `is_active` to `highlight` and added help text.  This is now the only qualifier for inclusion in home page rotation (although project must still be published).
-  Admins no longer see draft content anywhere on the site (disabled until/if we add a visual indicator for draft content so it can be distinguished from published content)

**Comment by mnaydan** [comment]
Home page displays links to Upcoming Events and Project pages, but home page does *not* display any events or projects at all.

**Comment by rlskoeser** [comment]
I wonder if this is because upcoming doesn't include the current day?  I think it may also mean #24 isn't filtering correctly and showing only upcoming events.

**Comment by rlskoeser** [comment]
I think the projects weren't displaying because there weren't any that were marked as active and had a grant that spanned the current date.  I tweaked a date and it showed up.  Possibly also has bad current-day logic like the events.

**Comment by mnaydan** [comment]
We changed the dates on the events and they are now displaying on the home page. But for the projects, only Derrida is showing up, even though others are "current" according to the calendar.

**Comment by rlskoeser** [comment]
That's because the `is_active` flag isn't set.  If you look at the list view, you'll see only Derrida has it set.  But it does seem redundant since we ought to be able to determine active projects based on grant dates.  

I'll follow up with @jabauer to see if she can remember why we added it and if there's still a need for it.

**Comment by kateclairmont** [comment]
Three upcoming events display on homepage. Four random projects that are marked "highlighted" in the admin display on homepage. Problem: thumbnail picture not displaying on homepage for Events or for projects.

**Comment by jabauer** [comment]
Thumbnail pictures now appearing when available.
