### ISSUE TITLE
project alums display incorrectly lists members of most recent grant

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#177]
# testing notes

on project pages, we show lists of people who have participated in the most recent grant, as well as "alums" (people who participated in past grants). for some projects, members that participated in the most recent grant were _also_ being displayed in the alums section. you can see the bug on the current website for the [derrida's margins project page](https://cdh.princeton.edu/projects/derridas-margins/): jean, ben, and xinyi are listed twice and appear in the alums section.

to test, visit some project pages on the test site ([derrida's margins](https://test-web.cdh.princeton.edu/projects/derridas-margins/), for example) and verify that nobody is listed twice. the s&co project page is also a good one to test with, since there's a lot of alums.

# dev notes
see also #164

**Comment by cvansant** [comment]
No double listing with Derrida, S&Co, or PPA, though Derrida does not have an alum section on the test site (and also the S&Co names are super outdated)

**Comment by cvansant** [comment]
No double listing with Derrida, S&Co, or PPA, though Derrida does not have an alum section on the test site (and also the S&Co names are super outdated)
