### ISSUE TITLE
As a user, I want to view and download files associated with pages on the site so that I can access other materials related to the content.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#18]
## Notes for testing
- should be visible on content pages, blog posts, projects, events, profiles

**Comment by rlskoeser** [comment]
@bwhicks what's current behavior? What kind of pages can have attachments right now?

**Comment by rgmunson** [comment]
Was able to successfully download attached file from a page, project page, and a staff page and to link from an attached URL to a page where resource download was available. I didn't test on the blog or events page but assume they'll behave the same way!
