### ISSUE TITLE
As a moderator, I want to create and edit projects in wagtail so that I can manage projects just like other pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#182]
# testing notes
## as a moderator
to test this, log into the new admin site (`/cms`) and check to see if you have a menu on the left side called "Projects".

1. Make a new project by going to the "Projects" menu, choosing "Project", and clicking "new project" at the top right. Feel free to also give the project an image/thumbnail and create some fake grants for it at the bottom. Make sure to add at least one membership to the project as well, down by where the grants are.
2. Visit the project's page by clicking "preview" at the bottom. Check that the project page is visually similar to current CDH project pages. The picture displayed should be the main image you uploaded to the project (not the thumbnail). The page should display the membership you added to the project and any grants you added.
3. Go back to the projects menu and choose "memberships". Are you able to find the membership you created when you made your new project in step 1? Try adding more memberships to your new project using this menu. Going forward, you can add memberships here, or directly on the project - whichever is easier.
4. Visit the project page again and check that the memberships you added in step 3 are now visible also.

moderators can also manage the list of available project roles, and manage the list of available grant types.

1. Create a new project role by going to the "Project" menu, choosing "Roles", and clicking "add role" at the top right. Don't worry about "sort order"; anything is fine.
2. Give any of the project members that you created in the steps above this new role.
3. Check the project page you created above and see if the list of members has been updated with the new role.
4. Create a new grant type by going to the "Project" menu, choosing "Grant Types", and clicking "add grant type".
5. Add a new grant to the project you created above like you did in step 1 above.
6. Check the project page again and see if your new grant is listed.

# dev notes
<s>going to leave `Membership` and our project association structure largely unchanged for now, but will revisit (potentially in v3.1) to improve it - likely by associating `Person`s to `Project`s directly.</s> done
## models
- [x] `Project` (becomes `Page` subtype, uses wagtail image fields, adds tags)
- [x] `ProjectQuerySet` (minimal changes)
- [x] `GrantType` (minimal changes)
- [x] `Grant` (minimal changes)
- [x] `Role` (minimal changes)
- [x] `Membership` (minimal changes)
- [x]  `ProjectLandingPage` - create special `LandingPage` subtype; cf. `PeopleLandingPage`
## admin
- [x] create a new section in the admin for Project-related models using `ModelAdmin`
- [x] set up the main admin for `Project`s (use `ProfilePage` as an example)
- [x] make `Membership`s inline-editable on `Project`s
- [x] make `Grant`s inline-editable on `Project`s
- [x] add an admin menu for creating new `GrantType`s?
## urls
all can be removed.

**Comment by manawinters** [comment]
I created a [new project](https://test-web.cdh.princeton.edu/cms/pages/383/edit/?next=/cms/projects/project/), and included an image, grant, and membership. I was able to "Save Draft," but when I select "Preview," I get the chicken error message. Therefore I wasn't able to get past step one, unfortunately.

**Comment by thatbudakguy** [comment]
@manawinters give this another try; I think we've fixed the issue with previewing.

**Comment by manawinters** [comment]
@thatbudakguy, I tried creating a [new project](https://test-web.cdh.princeton.edu/cms/pages/add/projects/project/4/), and got the error message, "The page could not be created due to validation errors"
