### ISSUE TITLE
As a moderator, I want to create and edit events in wagtail so that I can manage them just like other pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#184]
# testing notes
## as a moderator
to test this, log into the new admin site (`/cms`) and check to see if you have a menu on the left side called "Events".

1. Make a new event by going to the "Events" menu, choosing "Event", and clicking "new event" at the top right. Feel free to also give the event an image/thumbnail and add other details, including speakers if you want.
2. Visit the event's page by clicking "preview" at the bottom. Check that the event page is visually similar to current CDH event pages. The picture displayed should be the main image you uploaded to the project (not the thumbnail). The page should display the detail you added to the event, including speakers and other data.
3. Try clicking the "export to iCal" button on the left and see if your browser downloads a file (it may offer to open it with your calendar app). this should work the same way as in production. if you download the event, check that the event details on your calendar match the ones on the test site.

moderators can also manage the list of locations and available event types.

1. Create a new event type from the "Events" menu on the left.
2. Give the project that you created above this new event type.
3. Check the project page you created above and see if the event type has been updated.
4. Create a new location from the "Events" menu on the left.
5. Add the location to the event you created above like you did in step 2.
6. Check the project page again and see if your location is listed.
# dev notes
`EventIndexPage` is notable because it uses by-semester view filtering logic, which we haven't done on the wagtail side before. we can try using wagtail's `RoutablePageMixin` and if that fails fall back to the s&co implementation.
## models
- [x] `Event` (convert to Wagtail page model, change image fields, add tags).
- [x] `EventTypeManager` (minimal changes)
- [x] `EventType` (minimal changes)
- [x] `EventQuerySet` (extends `PageQuerySet`)
## admin
- [x] `EventType`, uses modeladmin, editable by Moderator only
- [x] `Event`, uses modeladmin, remove from page tree, editable by all users
- [x] `Location`, uses modeladmin, editable by all users?

**Comment by thatbudakguy** [comment]
bumping to 3 to account for new tests and possibly views

**Comment by thatbudakguy** [comment]
bumping to 5 to account for testing (by proxy) `LastModifiedMixin`

**Comment by thatbudakguy** [comment]
moved back to a 3; split off views to #286

**Comment by manawinters** [comment]
@thatbudakguy , I tried to create a new event (step 1), and got the 500/chicken error message.

**Comment by thatbudakguy** [comment]
@manawinters OK, I think I've fixed the underlying issue. go ahead and try creating a new event again.
