### ISSUE TITLE
show staff affiliates on affiliates page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#192]
# testing notes
you can see the new affiliates page [on the test site](https://test-web.cdh.princeton.edu/people/affiliates/). Joshua Seufert, a PUL librarian who received a DCG, should be displayed along with Kat Reischl. (in production, we'll need to create a profile for Joshua for this to work, since he doesn't have one yet – but then he will automatically appear).

# dev notes
see [slack conversation](https://cdhprinceton.slack.com/archives/C2VHT183A/p1596485281001400) for context - tl;dr we need to support showing PUL librarians who received DCGs on the affiliates page.

- [x] change "faculty affiliates" page title to "affiliates"
- [x] alter or add queryset methods to `ProfileQuerySet` to support querying for staff with the Project Director role
- [x] ensure that CDH staff and students remain excluded from display on the affiliates page
- [x] change url; add redirect from old url to new (redirectview or migration to add redirect rule, whichever is easier/makes more sense)

relevant portion of `models.py`:

https://github.com/Princeton-CDH/cdh-web/blob/95d2ad778d426eab2d6f1419b91a978f5293da2f/cdhweb/people/models.py#L169-L173

**Comment by cvansant** [comment]
looks good
