### ISSUE TITLE
As an admin, I want to add a virtual location to events so that people know they can join remotely.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#194]
# testing notes
a couple things have changed here that we need to test.
- if you go to the [list of event locations](https://test-web.cdh.princeton.edu/admin/events/location/) and create a new event location, you have the option to mark a location as virtual. Try it by creating a location for "Zoom" or similar.
- formerly, addresses for locations were required. Now, they are no longer required _if_ the location is virtual. Try this by saving a virtual location without an address. Also, try to remove the address from an existing non-virtual location and save it (this should produce an error).
- you can sort the list of locations by whether they're virtual by clicking the header "Virtual" in the list.
- if you go to the [list of events](https://test-web.cdh.princeton.edu/admin/events/event/), you should see that events with a virtual location are also marked virtual.
- if you edit an event, there should be a new property called "Join URL" (should be below "attendance" if you scroll down) for adding the Zoom link for an event.

(so far, there's no visual indication on the actual website that events or locations are virtual besides their name, but we added hidden metadata that should allow people to easily use the zoom link if they find the event via google.)

# dev notes
Revise event to support new schema.org virtual event location
- add a field for admin to include this
- update the template to render the location
- include in schema.org structured data

**Comment by cvansant** [comment]
Everything worked for me.
