### ISSUE TITLE
affiliate grant year ranges on profile list pages are incorrect

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#197]
this is issue affects the display of grant information on the profiles of current affiliates. because the page tries to display the full range of years that someone has had _any_ grant (for example, S&Co. has had grants for 5+ years), it creates a year range to display.

the issue is that it only displays the _name_ of the most recent grant, so it will write something like `2015-2021 Dataset Curation Grant` which is wrong - the dataset curation grant was only for 2021.

the easiest solution for now is to simply not display the range, so that the information is at least technically correct. thus people who got multiple grants will only display the most recent one, i.e. `2021 Dataset Curation Grant`.

when we have a workable solution to display ranges again, that will be tracked on #222.

for more context, see slack conversation: https://cdhprinceton.slack.com/archives/C2VHT183A/p1599587576088900

# testing notes
- Josh and Kat Reichl are good candidates to test this with, since both of them are currently displaying ranges that are incorrect in production.
- All profiles on the affiliates page in the "current" section should only display the most recent grant (so all dates should be this academic year).
- All profiles on the affiliates page in the "past" section should be unchanged; just give a quick to look to make sure that nothing looks off.

**Comment by thatbudakguy** [comment]
moving out of v2.7 since there's not an easy solution and right now it only affects a few profiles.

**Comment by thatbudakguy** [comment]
if we implement the simplest fix (just display most recent grant), need to make an enhancement to later improve the display again.

**Comment by cvansant** [comment]
@thatbudakguy Looks fine! Only thing is that the link to Reischl's page in Slavic doesn't work. Here is the new link: https://slavic.princeton.edu/people/katherine-hill-reischl
