### ISSUE TITLE
As a user I want to see a list of current projects so I can learn more about the work of CDH.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#20]
## Notes for testing
- Project list page should be accessible from the top-level navigation (I added a placeholder link to the test site), or by clicking the projects heading on the home page.
- I just noticed the user story says "current projects", but it's not actually filtered right now (except based on published/unpublished).  I think we should revise the user story to say all projects since that matches the current site functionality, and add a feature later to revise project display (filters, project archives, or something).
- Note that a logged admin can see unpublished content.  We plan to add a visual indicator for draft content, but that won't be included in this release.
- Projects are currently sorted by title.

**Comment by mnaydan** [comment]
Was able to access project page via home page and header menu. Was able to see projects listed on project page and click on individual projects. Clicking on individual projects directed to individual project pages.
