### ISSUE TITLE
As a user, I want to learn about the DH Working Groups sponsored by the CDH.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#211]
**Is your feature request related to a problem? Please describe.**
The CDH has now sponsored at least three major working groups on campus. We need a place on the website to highlight these groups and link to their websites, where applicable.

**Describe the solution you'd like**
The simplest solution seems to be to represent working groups as projects, since they:
- will often be grant-funded (in all 3 current cases, a CDH seed grant)
- can be associated with people already in the CDH database via roles
- will need a list page that shows all of them together
- will need detail pages that include information along with a list of members and a link to the group's website

To do this, we could start by:
- [x] adding a flag to `Project` to indicate if it's a working group
- [x] add the ability to set the working group flag in the admin interface
- [x] adding a new `ProjectListView` in django that gathers all working group projects as its context
- [x] adding a new route to the Project `urls.py` that ties a url like `/projects/working-groups` to the new view
- [x] adding a new page in mezzanine underneath "Projects" that has the above URL, and ensuring it appears in the nav
- [x] optionally adding some new working group membership roles like "Chair" and "Co-Chair"

Then, new working groups could be created by:
- creating a new `Project` in the admin, and marking it as a working group
- editing the new `Project`'s page to add a link to the group's website and some info
- create and associate any grants given to the group, such as a Seed Grant
- add members of the working group via memberships on those grants

**Describe alternatives you've considered**
Each working group could simply be a basic page with no special logic, if the above approach doesn't work. They would still need a page somewhere on the site to aggregate all of the working groups and list them, which would need to be manually updated.

# testing notes
- The East Asian DH, South Asian DH, and Slavic DH working group pages should all now be accessible on a new page under projects called "Working Groups".
- If you create a new Project and check the "working group" box, it should also show up on the working groups page.

**Comment by thatbudakguy** [comment]
ask natasha whether WGs have an endpoint, like grants, or whether they're "forever" (in which case we can just key on a flag set on the `Project`).

**Comment by cvansant** [comment]
Yes, this works. I added (and then deleted) an imaginary working group, as well.
