### ISSUE TITLE
As a user, I want to see PGRA profiles listed with students and postdoc profiles listed with staff, so I understand how these people relate to the CDH.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#217]
See #218, which operates according to the same logic: display people based on how closely they work with CDH.

- having PGRAs with postdocs implies that they are similarly closely associated with the CDH, which isn't true
- postdocs are much more like staff, and PGRAs are more like students than postdocs

# testing notes
- former PGRAs like Sean Fraga, Jessica Mack should display in the past section of the Students page
- all current and former postdocs should display on the Staff page
- Camey (former PGRA, current postdoc) should display on the Staff page but will also show on the Students page because of being project manager on S&Co

**Comment by thatbudakguy** [comment]
For the postdocs:
- [ ] Remove the postdocs page
- [ ] Remove the `not_postdocs()` constraint on the staff page view
- [ ] Add a redirect from the postdocs page URL to the staff page URL
- [ ] Remove the `postdocs()` and `not_postdocs()` queryset methods

**Comment by cvansant** [comment]
@thatbudakguy This works except that the menu item "postdocs" is still there, but the page isn't. Also idk if I should be a student because of S&Co (though it's fine if you want to do it that way). I was never PM for S&Co as a student (I became PM in July). But I was a regular PGRA in the spring.

**Comment by thatbudakguy** [comment]
thanks for pointing it out - rsk mentioned that there was an easy way to make sure you aren't double-listed, so I tried that and you're now only on the staff page. I also removed the link to the old postdoc page from the menu.

gonna close this but feel free to reopen if it doesn't look right to you.
