### ISSUE TITLE
As a user I want to view a list of staff members so I can get an idea of the people who work at the CDH.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#22]
## Notes for testing
To be included in the list, people must be marked as `is_staff` and profile must be published.

**Comment by rlskoeser** [comment]
@bwhicks new database model is designed to support alums but I think we should probably leave that out of this release.

**Comment by mnaydan** [comment]
Staff members (pictures, names, titles) viewable in block format via Staff page on top header. FYI: they display alphabetically by last name instead of title.
