### ISSUE TITLE
As an admin, I want to create staff projects that aren't R&D and have them show up on the Staff Projects page so I can highlight new work like Startwords.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#221]
We already have a "staff projects" grant type, but it isn't configured to make projects display here. Just need to edit:
https://github.com/Princeton-CDH/cdh-web/blob/96404f5296d0cd9973d21530c3e540813243bd62/cdhweb/projects/models.py#L42

and include it.

After this is done, change the Startwords project grant type back to "staff projects".

# testing notes
when this is working, you should be able to find "Startwords" under "staff projects". If you click it and scroll down to the bottom to see the list of CDH grants, it should read "Staff Projects" (_not_ "Staff R&d").

**Comment by cvansant** [comment]
Looks good--only thing is that it says "2019– staff project," and that's a bit confusing.

If the dash just means "2019 to present," I guess that's fine. But the dash looks a little bit like a hyphen, like it means something equivalent to "2019: staff project."
