### ISSUE TITLE
test copying uploaded media to new QA machine

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#226]
we'll need an automated procedure for syncing uploaded files and media to the new QA machine that we can run once at the start of the migration process, and at least one final time at the end before we make the switch.

**Comment by thatbudakguy** [comment]
according to its `man` page `rsync` doesn't support copying between two remote hosts (one must be localhost), so I ended up doing the media transfer with `scp` because it has an option to move files between two hosts using localhost as a middleman. this also means there's no need to mess with proxying options, because `scp` just reads your `ssh` config file, so it will access the hosts in the same way you would via `ssh`.

to transfer the media folder to QA, for example, I did:
```sh
$ scp -rpv3 cdhweb-old:/srv/www/media/ cdhweb-qa:/srv/www/
```
where:
- `cdhweb-old` is an alias for `cdh.princeton.edu` which proxies thru `libservdhc7` and logs in as `deploy`
- `cdhweb-qa` is an alias for `cdh-test-web1.princeton.edu` which logs in as `pulsys`
- `-r` copies the directory recursively
- `-v` displays extra stats in case it fails
- `-p` preserves permissions on files (they'll still be owned by `pulsys` on the target machine)
- `-3` proxies the transfer through my local machine, which makes the `ssh` aliases above work correctly

note also the lack of `/media` on the second path, otherwise we'll get `/media/media`.

this command takes quite awhile to run to completion. unfortunately `scp` isn't as smart as `rsync` when it comes to copying, so we'll just have to clobber everything in the destination each time we run it.

**Comment by rlskoeser** [comment]
@thatbudakguy I had imagined sshing into the new server and running the rsync command there to transfer content directly from the old server to the new one. Wouldn't that be more efficient / effective?

**Comment by thatbudakguy** [comment]
to do that, the new servers need to know how to proxy through `libservdhc7` to get to the old production instance. it seemed simpler to just run it on my machine, which has that already set up in my `ssh` config.

i don't think `conan` has permission to write to `/srv/www/media`, so it needs to be `pulsys` to do the transfer (but we can `chmod` it afterward).

**Comment by rlskoeser** [comment]
@thatbudakguy why is the proxy needed? We can request RC allow access from the new IP if that's the problem (likely a trivial change for them). I think the efficiency of using rsync and keeping the transfer within the same network is worth it!

Let's make sure we figure out media directory ownership as part of testing the deploy. Would be nice to have it set properly at the outset.

**Comment by rlskoeser** [comment]
Testing using rsync from production old cdh web to new pul test server.

- manually created new ssh key for conan user on cdh-test-web1
- manually copied new public key to deploy user authorized keys on cdh-web
- created new test directory for media in tmp just to check the process
- ran rsync with these options:
`rsync -az --stats deploy@cdh-web.princeton.edu:/srv/www/media/uploads media`

Output is pretty verbose with those options, but nice to see what's happening.

Stats reported:
```
Number of files: 3,180 (reg: 2,203, dir: 977)
Number of created files: 2,295 (reg: 1,859, dir: 436)
Number of deleted files: 0
Number of regular files transferred: 1,859
Total file size: 1,402,599,027 bytes
Total transferred file size: 952,300,431 bytes
Literal data: 952,300,431 bytes
Matched data: 0 bytes
File list size: 139,569
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 39,345
Total bytes received: 916,075,327

sent 39,345 bytes  received 916,075,327 bytes  17,123,638.73 bytes/sec
total size is 1,402,599,027  speedup is 1.53
```

I also ran it with `time` to see how long syncing everything took:
```
real	0m52.887s
user	0m15.999s
sys	0m7.951s
```

**Comment by rlskoeser** [comment]
Tested and documented.
