### ISSUE TITLE
As an admin, I want to associate project contributors with projects based on the dates they were involved instead of by grant, so that I can accurately reflect project team membership over time.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#233]
## testing notes

Project membership has been revised and now is linked to the project instead of a particular grant, and project memberships have start and end dates of their own distinct from the grants. This update adds those fields, removes the old override status, and auto-calculates start and end dates based on the information in the database. (We expect that some manual correction of calculated dates will be needed afterwards.)

- review project memberships in the admin; you may want to compare with production in some cases
  - check that people who were involved on multiple subsequent grants for a single project now have a single membership entry with combined date ranges with the start of the earliest grant and then end of the most recent grant (examples: project directors on multi-year projects like S&co or PPA)
  - check people who've had multiple roles on a single project have multiple membership records (S&co has some)
  - check that cdh staff who left a project before a grant ended have an earlier end date, based on their position dates (examples: Ben, Xinyi, Jean)
   - check that cdh staff who joined cdh after a project had already started have their cdh start date instead of the grant start date (examples: Nick, Kevin)
   - check that people who had overrides with status "current" in production have no end date set on the corresponding membership (PPA and S&co have some examples)
- check that you can create a new membership; start date should be required now
- check that project pages on the public site display as expected with current team members and alums
- check that affiliate and student pages display correctly

---- 

This change should solve some problems, including specifically #212 

- [x]  add start and end dates to project membership model (both optional for now)
- [x] write a migration to calculate best guess for start and end dates by aggregating memberships by person and role, and using associated grant dates; for CDH staff, use start and end dates as additional limits; remove any extra memberships when multiples are combined into a single range
- [x] create log entries in the migration to document the date calculation
- [x] remove grant and status override fields on project membership
- [x] update project membership admin list and edit views to use the new fields and remove the old ones
- [x] revise project admin page to use the new fields and remove the old ones; if including memberships on project page for large projects is still too slow, remove it
- [x] update project detail page to find and retrieve current and past project members based on dates on the membership instead of the grant
- [x] update impacted affiliate pages to use dates on membership instead of grant to determine whether they are current or past
- [x] write unit tests for date calculations migration

**Comment by rlskoeser** [comment]
@thatbudakguy I think, given the number of pieces this touches plus the addition of log entry and script account, this is a 5. LMK if you disagree.

**Comment by cvansant** [comment]
- Elspeth Green has two S&Co PM entries, and two S&Co researcher entries
- check that cdh staff who joined cdh after a project had already started have their cdh start date instead of the grant start date (examples: Nick, Kevin) [For this one, you and Kevin have a variety of start dates for the project. I assume this just reflects the fact that you didn't start all the projects on your first day at the CDH, but I'm noting it just in case]
-PPA page lists Mary Naydan as an alum rather than as PM

**Comment by rlskoeser** [comment]
- Huh, interesting about Ellie. I had a question in the comments about whether or not I needed to sort by role, I guess I should have. I think they must have not grouped correctly.  
- I'm not sure what you're saying about the staff start dates; it should either be the start of the grant or the start of their time working with cdh, which is what I think I see
- Mary isn't actually listed on the current PPA grant in the production database, so this reflects the data we have accurately (even though the data is wrong).

**Comment by cvansant** [comment]
About #2 (sorry I wasn't clear): What I meant was that Kevin and Nick's start dates on projects do not all correspond with their start dates at the CDH. Kevin's CDH start date is March 30. However, his start date on Mondrianify is Sept 2; PPA is July 1; and Geniza is Sept 20. These do in fact correspond with the grants (as long as he didn't participate in an earlier PPA grant), so I guess we're fine.

Ellie was the only person where anything appeared incorrect.

**Comment by cvansant** [comment]
Update: there was no 2019-20 PPA grant so looks correct (except for the Ellie issue)

**Comment by rlskoeser** [comment]
@cvansant thanks for clarifying!

@thatbudakguy if Ellie is the only one impacted by this other problem, it's not much work to clean up manually (and we know we have other manual cleanup to do anyway); even if she isn't the only one, it's hard to imagine there are very many. The other option is to include `role` when ordering the memberships for consolidation in the migration that calculates dates.

**Comment by thatbudakguy** [comment]
> The other option is to include role when ordering the memberships for consolidation in the migration that calculates dates.

This sounds like the simplest thing to me, unless you think it's more work to make the change?

**Comment by rlskoeser** [comment]
@thatbudakguy I think the change is pretty simple, it's the redeploying and re-testing. (Although now that I look I'm not sure whether role sort needs to be before or after the grant start date 🤔 ... but should be easy enough to test.)

I just remembered, I forgot to ask Camey to check the history! @cvansant could you check a few of the memberships to look at the history and confirm there's a log entry indicating the dates where set? The user who made the change should be "script".

**Comment by rlskoeser** [comment]
@cvansant I've revised the logic slightly and re-run the migration, would you confirm that it fixes the duplicate memberships for Ellie?

**Comment by cvansant** [comment]
@rlskoeser Correct--only one Ellie PM, only one Ellie Researcher!

**Comment by cvansant** [comment]
@rlskoeser @thatbudakguy checked history!
