### ISSUE TITLE
meta information for project pages is incorrect

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#237]
**Describe the bug**
The metadata for project list pages is incorrect, leading to strange-looking embeds:
<img width="622" alt="Screen Shot 2020-11-16 at 5 26 53 PM" src="https://user-images.githubusercontent.com/4924494/99315690-00fcad00-2831-11eb-878f-1551eb34fedf.png">

**Expected behavior**
- Each project page should have a correct `title`, instead of using "Sponsored Projects" for all of them
- The project pages should either display some actual content for the `description`, or get rid of the `&nbsp;` filler
- Check other metadata?

- [x] migrate keywords to tags and list them in the `head`

**Comment by rlskoeser** [comment]
updates and events pages have no og:title or twitter:title 

same for project list views (sponsored, staff, working group); for the views, title is set in context as `page_title`, which should be used as a fall-back choice after `page.title` — but I see it is in our list; maybe we need to switch the order?

would be nice to include page intro text on working group as page description, but that one's not a deal breaker
