### ISSUE TITLE
As a user I want to view a list of upcoming events so that I can find and attend events that interest me.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#24]
## Notes for testing
- Event list list page should be accessible from the top-level navigation (I added a placeholder link to the test site), or by clicking the events heading on the home page.
- Currently displays upcoming events only; event archive functionality still needs to be done and will be tested separately.

**Comment by rgmunson** [comment]
Full event list can be accessed through the header on the homepage and "upcoming events" display when you click the icon on the homepage. As Ben's comment says, only upcoming events are in this list (archive functionality will be a separate issue).
