### ISSUE TITLE
set up visual regression testing

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#240]
- [x] install percy and dependencies
- [x] create python/selenium script to run test server and take DOM snapshots to send to percy
- [x] add github actions workflow for running script
- [x] add test site fixture function based on new pytest fixtures; clean up old/unused fixtures
- [x] set up slack notifications for percy
- [x] update README

**Comment by thatbudakguy** [comment]
see https://github.com/Princeton-CDH/cdh-web/pull/260
