### ISSUE TITLE
As a content editor, I want existing content pages migrated from mezzanine to wagtail so that I can manage them in the new system.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#244]
# testing notes
see the **fyi** section on #180 before testing this, if you haven't read it yet.

as part of the v3.0 upgrade, we are using a script to convert all of the old pages (the ones in `/admin`) into their new counterparts (the ones at `/pages` URLs, which are editable in `/cms`). we're calling this process the "exodus", because it isn't quite a migration. this issue (and others like it) are for testing that certain kinds of pages were "exodized" correctly - that the new versions got created and work just like the old ones (or better!)

for this issue, we need to check that three types of pages were correctly "exodized" and are available under `/pages`:
- the homepage (`/pages/`)
- all the landing pages (`/pages/people`, `/pages/research`, `/pages/projects/about`, `/pages/engage`)
- all the content pages (too many to list here)

notice that `/events` and `/updates` are not landing pages; they're special and will be tested on #252 and #250 respectively. also, `/projects/about` is special - we wanted `/projects/` to just be a list of projects, so the actual landing page is at `/projects/about`. make sure you go to `pages/projects/about` to test it.

- for the homepage and landing pages, load up the current site (cdh.princeton.edu) and just do a quick comparison to make sure nothing looks out of place in the new counterpart.
- for the content pages, you can explore the pages tree in wagtail and just pick a few to examine; anything under `/engage` is a safe bet. stay away from `/projects`, `/events`, `/people`, and `/updates` – most of those special pages haven't been "exodized" yet, so you'll see a lot of blank pages. we'll be testing them later.
- make sure to also test the two embedded forms `/pages/events/cosponsor` and `/pages/engage/consult`; these are sorta "special" but we made them part of this issue, so they should work.

# dev notes
depends on #180 

this will be a script that can be run by a manage command that uses the tools prototyped in #243 to query for all the existing content page (content page, landing page, homepage) and create their new wagtail versions from #180.

likely order is homepage first, then landing pages, then content pages. probably we will have logic like "if this page's parent hasn't been migrated, do that first, then create it as a child of the parent". maybe we can do something clever and request a flattened page tree from mezzanine so that we do it in top-down order.

- [x] migrate homepage
- [x] migrate landing pages
- [x] migrate content pages (recursively)
- [x] ensure page visibility status (draft/published) is migrated
- [x] generate simple report of pages with keywords so data is not lost (but do not migrate)
- [x] ensure embedded forms are preserved (consult, cosponsor)

**Comment by rlskoeser** [comment]
Investigating keyword usage on current content:
- 2 of 57 content pages use keywords
- 14 of 208 blog posts use keywords

```
 Page.objects.exclude(keywords_string='')
<SearchableQuerySet [<Page: Engage / Graduate Students / Graduate Fellowships>, <Page: Engage / Graduate Students / Graduate Travel Grants>]>
>>> Page.objects.exclude(keywords_string='').values_list('keywords_string', flat=True)
<SearchableQuerySet ['graduate students grad grants graduate students fellowships', 'grants graduate students travel']>
>>> BlogPost.objects.exclude(keywords_string='')
<BlogPostQuerySet [<BlogPost: Still Speaking in Code>, <BlogPost: Best Practices?>, <BlogPost: Lessons learned from building “Derrida’s Margins”>, <BlogPost: Designing for Jacques Derrida>, <BlogPost: Princeton Prosody Archive: Rebuilding the Collection and User Interface>, <BlogPost: Bridging Digital Humanities Internal And Open Source Software Projects Through Reusable Building Blocks>, <BlogPost: The CDH at DH2018>, <BlogPost: CDH Web 2.0 is live!>, <BlogPost: Why and How We Test Software>, <BlogPost: Fall Visiting Speaker: Deb Verhoeven>, <BlogPost: The One Where There Are Two New Post Docs at the CDH>, <BlogPost: Meet Our (New) Graduate Students!>, <BlogPost: So Long, and Thanks for All the Muffins>, <BlogPost: Project Managers and Designers - Meet up at DH 2017!>]>
>>> BlogPost.objects.exclude(keywords_string='').count()
14
>>> BlogPost.objects.count()
208
>>> BlogPost.objects.exclude(keywords_string='').values_list('keywords_string', flat=True)
<BlogPostQuerySet ['origin story', 'software development projects fallibility process', 'software development lessons learned mistakes process', 'design', 'DH2018', 'software development DH2018', 'DH2018', 'software development', 'testing software development fallibility', 'Workshop lecture visiting speaker', 'postdocs CDH community Workshop projects', 'graduate students CDH projects grad caucus collaboratories', 'DH2017 meetup projectmanagement projectdesign community storify', 'DH2017 meetup projectmanagement projectdesign community']>
```

Let's not worry about migrating them to wagtail, but generate a quick report of url + keywords so we have the data.

**Comment by rlskoeser** [comment]
Report on pages with keywords:

graduate-fellowships | Graduate Fellowships | graduate students grad grants graduate students fellowships
engage/graduate-students/graduate-travel | Graduate Travel Grants | grants graduate students travel


blog pages with keywords:
still-speaking-code | Still Speaking in Code | origin story
best-practices | Best Practices? | software development;projects;fallibility;process
lessons-learned-building-derridas-margins | Lessons learned from building “Derrida’s Margins” | software development;lessons learned;mistakes;process
designing-jacques-derrida | Designing for Jacques Derrida | design
princeton-prosody-archive-rebuilding-collection-and-user-interface | Princeton Prosody Archive: Rebuilding the Collection and User Interface | DH2018
dh2018-reusable-software | Bridging Digital Humanities Internal And Open Source Software Projects Through Reusable Building Blocks | software development;DH2018
cdh-dh2018 | The CDH at DH2018 | DH2018
cdh-web-20-live | CDH Web 2.0 is live! | software development
why-and-how-we-test-software | Why and How We Test Software | testing;software development;fallibility
fall-visiting-speaker-deb-verhoeven | Fall Visiting Speaker: Deb Verhoeven | Workshop;lecture;visiting;speaker
the-one-where-there-are-two-new-post-docs-at-the-cdh | The One Where There Are Two New Post Docs at the CDH | postdocs;CDH;community;Workshop;projects
meet-our-new-graduate-students | Meet Our (New) Graduate Students! | graduate;students;CDH;projects;grad;caucus;collaboratories
so-long-and-thanks-for-all-the-muffins | So Long, and Thanks for All the Muffins | DH2017;meetup;projectmanagement;projectdesign;community;storify
project-managers-and-designers-meet-up-at-dh-2017 | Project Managers and Designers - Meet up at DH 2017! | DH2017;meetup;projectmanagement;projectdesign;community

**Comment by cvansant** [comment]
@thatbudakguy These look good!

Just reminding you about the url inconsistency:
On the live site (cdh.princeton.edu), the "grants page" and all its subpages (e.g. research partnerships) do not have "engage" in the URL, even though they are underneath "engage."

On the test site with "pages", urls based on live site don't work (that is, /pages/grants give you an error). Rather, you need: /pages/engage/grants to get it to work. Thus, the research partnership "pages" page is pages/engage/grants/cdh-research-partnerships, NOT pages/grants/cdh-research-partnerships

**Comment by rlskoeser** [comment]
@cvansant thanks for flagging the url mismatch! We're thinking we can address/resolve when we tackle the menus so we can properly handle the mismatch between site hierarchy and navigation / menus.
