### ISSUE TITLE
As a moderator, I want existing related links migrated to wagtail so that I can manage them in the new system.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#249]
# testing notes
this is a companion to #181; you may find it easier to test that first. see that issue's notes for a description of what related links are and how they work.
## as a user
- visit a few project pages on the test site and check that all their related links are displayed, and that the display matches the project page on the current production site. try a sponsored project, a staff project, and a working group.
- visit a few profiles on the test site and check that all their related links are displayed, and that the display matches the profile on the current production site. staff and students are generally the only ones with profiles.
- find a person who doesn't have a profile (easiest with faculty affiliates) but who does have a website link. check that clicking them in the list view on the test site takes you to their website, just like it does on the production site.
# dev notes

**Comment by kmcelwee** [comment]
Testing Notes:
- [ ] Find a project with a related link on prod ([like the Natasha's NEH grant](https://cdh.princeton.edu/projects/new-languages-nlp-building-linguistic-diversity-digital-humanities/)) Make sure that that also exists in QA
- [ ] Compare related links on profiles for prod and QA and ensure that they are the same.

**Comment by cvansant** [comment]
@thatbudakguy The links aren't visible as far as I can tell. For instance, on the current site, Zoe has links to Github, Twitter, and her website: https://cdh.princeton.edu/people/zoe-g-leblanc/

[Here ](https://test-web.cdh.princeton.edu/pages/people/zoe-g-leblanc/)there are no such links

**Comment by manawinters** [comment]
@thatbudakguy , the only projects that appear in the test site are "Past Projects" under "Sponsored Projects." [Staff Projects](https://test-web.cdh.princeton.edu/projects/staff/) is blank and [DH Working Groups](https://test-web.cdh.princeton.edu/projects/working-groups/) goes to the description.

**Comment by manawinters** [comment]
Links and display of staff and students looks good. The only difference between the two sites are the Recent Posts - in the [test site](https://test-web.cdh.princeton.edu/pages/people/rebecca-sutton-koeser/) there is the post title, user name (rkoeser), date, and the first sentence of the post. In the [production site](https://cdh.princeton.edu/people/rebecca-sutton-koeser/), it just shows the post title and date.

There are no Affiliates listed on the [test site](https://test-web.cdh.princeton.edu/people/affiliates/).
