### ISSUE TITLE
As a moderator, I want existing projects migrated to wagtail so that I can manage them in the new system. 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#251]
# testing notes
companion to #182; you may want to do that first to get a sense of how projects look in the new system.
## as a user
- visit some project pages on the new site. does everything look similar to the corresponding project pages on the old site? try a sponsored project, a staff project, and a dh working group.
- note anything that looks off and leave a comment below.

# dev notes
depends on #182

**Comment by manawinters** [comment]
Sponsored Project: I looked at the Princeton Geniza Project -- the only differences were the Assistant Project Manager (Stephanie Luescher) is missing on the test site and Rebecca's name is listed as "Rebecca Sutton Koeser" in the production site but "Rebecca Koeser' in the test site.

Staff and Postdoctoral Project: I looked at Startwords and it appeared the same in both sites.

[DH Working Groups](https://cdh-test-web.princeton.edu/projects/working-groups/): Still only appears as a short description and no links to the projects in the test site.

**Comment by manawinters** [comment]
In re-testing #280, the drop down option in Projects in the test site is now working, and I am able to view the DH Working Groups projects that way. As mentioned above, however, when I go straight to DH Working Groups from Projects, only a description/no projects appear.

**Comment by thatbudakguy** [comment]
@manawinters can you confirm that you can now get to DH working groups and they show up (both ways)? if so, this is ready to close.
