### ISSUE TITLE
As a moderator, I want existing events migrated to wagtail so that I can manage them in the new system.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#252]
# testing notes
companion to #182; you may want to do that first to get a sense of how events look in the new system.
## as a user
- visit some event pages on the new site. does everything look similar to the corresponding project pages on the old site? try different kinds of events, like lectures, workshops, etc.
- remember that the test site will often be out-of-date with production, so any changes made in the last few weeks may not show in test. that's OK; you're looking for things that seem _wrong_ not things that are missing.
- note anything that looks off and leave a comment below.
# dev notes
depends on #184

**Comment by thatbudakguy** [comment]
reducing to a 1 since exodus could be adapted directly from projects, with some simplifications

**Comment by manawinters** [comment]
- The dropdown option does not work in the test site
- Names contain middle initials in the production, but not test site (eg. [Grant R. Wythoff](https://cdh.princeton.edu/events/2021/01/humanities-data-teaching-fellows-information-session/) in the Humanities Data Teaching Fellows Info Session)
- Otherwise events look the same on production and test sites

**Comment by thatbudakguy** [comment]
@manawinters i think the dropdown not working is actually because the "this is a test site" banner is in the way! can you try clicking OK on the banner and seeing if the dropdown works after that? it worked for me.

the name discrepancy is OK; I think we only want to use the profile title (the one with the middle initial) on the profile going forward. please close this if you are able to operate the dropdown after clicking OK on the test banner.
