### ISSUE TITLE
As an editor, I want to manage the menus displayed across the site in wagtail so that I can easily update them when needed.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#255]
## testing notes
- [ ] check that the main navigation matches what is in production
- [ ] check that the footer matches what is in production (expected exceptions: Contact & Directions and Credits should now be listed under Home; Admin has been removed)
- [ ] check a few landing pages to confirm that the pages under them display as attachment cards
- [ ] in wagtail, change the order of one or two top-level pages; reload the public site and confirm the main menu and footer reflect the order change you made
- [ ] in wagtail, edit a page that is in the menu and set it to not show in menus (on the promote tab); reload the public site and confirm that the page is no longer included in the menu

## dev notes
`wagtailmenus` is already installed.

- header/main nav: uses `wagtailmenus` "main menu"; make sure to [check out the "autopopulate" option](https://wagtailmenus.readthedocs.io/en/stable/installation.html). if autopopulate is wrong, consider an exodus step to correctly set up the menu. note that you can call manage commands from other commands; the main exodus script can call autopopulate and then modify if it needs to.
- footer nav: uses pages with `show_in_menus`; just shows 1st and 2nd level pages. not editable. make sure it includes things that are children of root/parallel like about, etc.
- child page nav: show all one-level-down children that have `show_in_menus`. does this match current production? if not, what are the outliers? can we live with them changing?

**Comment by rlskoeser** [comment]
Needs to handle top nav, footer nav, and parent page nav; consider splitting out page nav into a separate story.

**Comment by manawinters** [comment]
I'm getting an "[internal service error](https://cdh-test-web.princeton.edu/projects/sponsored/)" when I go to the attachment cards, despite a hard refresh.

**Comment by manawinters** [comment]
[People](https://test-web.cdh.princeton.edu/people/) drop down is out of order in test site -- instead of staff, students, affiliates, ec (as it is in production site), it reads "students, staff, ec, affiliates"

@rlskoeser, how do I "change the order of top level pages" in wagtail?

**Comment by rlskoeser** [comment]
@manawinters checking with @thatbudakguy to make sure  we ran the version of the exodus script that sets the order.

To edit page order — when you're looking at a list of pages in the wagtail edit interface, click the "sort" column heading — that will give you grabbable handles next to the titles that you can use to drag and drop pages within the order.

If you want to move a page to somewhere different in the hierarchy, there is a "move" option in the "more" menu.

**Comment by manawinters** [comment]
@rlskoeser, thanks. all above tests were successful. once the order of People is fixed, I will close out the issue.
