### ISSUE TITLE
As a user, I want to download event information as ical so I can add it to my personal calendar.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#26]
## Notes for testing
iCal download link is accessible on the event detail page.
### Testing Updates 9/5:
- Fixed timezone logic.  Please double check time display on project card, since I had to update that as well.  (You may have to update existing test events since the timezone configuration has changed).
- Test with and without location set.

**Comment by rgmunson** [comment]
iCal downloads and integrates successfully but, for some reason, it shifts the time back 4 hours. It did this for both me and Mary so we think it must be the download rather than our computer settings. Maybe it wants us to be in Hawaii?

**Comment by rlskoeser** [comment]
I must have gotten the timezones wrong, I'll look into it.

**Comment by rgmunson** [comment]
Tested the iCal export using information imported from previous version of CDH web (with info for event taking place tomorrow). The time does display on the project card. The export works with the correct time zone. The download works properly whether or not the location is set (and if it is set, the info is there).
