### ISSUE TITLE
add apache rewrite rule to ansible for migrated media

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#264]
I think the apache rewrite rule we want should be something like this:
```
RewriteEngine On
RewriteCond "%{REQUEST_URI}"  "^/media/uploads" 
RewriteRule "/(.*\.(jpg|jpeg|gif|png))$" "/media/original_images/$1" [L,R=301]
```
It's not working in an online regex tester but I'm not sure why, and this is pretty close to some of the examples in the apache documentation, so hopefully it will work with a little testing and tweaking.

@thatbudakguy how/where should we track adding this to our deploy apache conf? We can't add it yet or because will break cdhweb 2.8.1.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/cdh-web/issues/248#issuecomment-748313736_

**Comment by thatbudakguy** [comment]
confirmed working by testing two different images at their old URLs, which successfully redirected with a 301 (embedded in blogpost and featured on project page).
