### ISSUE TITLE
As a user, I want to view previous events by semester so that I can get a sense of event and workshop offerings.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#27]
## Notes for testing
- links to archive are not styled yet, but logic should be working

**Comment by kateclairmont** [comment]
I can view events by year and see the details about the event. Images show up when I click into an individual event. However, the thumbnail does not display consistently.

**Comment by rgmunson** [comment]
I'm able to view events by year (ordered chronologically) as well as by "upcoming." All works!

**Comment by rlskoeser** [comment]
Reopen and changing to view by semester.

**Comment by jabauer** [comment]
Semester filtering works and is in the correct order.
