### ISSUE TITLE
Embed sizing ignores container margins on mobile

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#273]
**Describe the bug**
Embedded content, such as videos, is able to escape the width of the page and cause it to have a horizontal scrollbar.

**To reproduce**
1. Visit the site homepage on a mobile device (<768px width)
2. Scroll down until you reach the embedded video about the cdh
3. Observe that it extends outside the viewport to the right

**Expected behavior**
Embeds should be resized to fit the container width.

**Screenshots**
<img width="403" alt="Screen Shot 2021-01-11 at 2 21 19 PM" src="https://user-images.githubusercontent.com/4924494/104228035-4942e080-5418-11eb-82b0-211738ee9298.png">

**Device information**
tested on FF v85 mobile device emulator on OSX 10.15.7

**Comment by cvansant** [comment]
Looks good!
