### ISSUE TITLE
fix temporary models and model fields

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#285]
several model fields and settings are in a temporary state that needs resolving in 3.0.1.
# People
- [x] `OldProfile` should be removed
# Projects
- [x] `OldProject` should be removed
- [x] `Grant.project` should use the `models.CASCADE` deletion handler and not allow null
- [x] `Grant.old_project` should be removed
- [x] `Membership.project` should use the `models.CASCADE` deletion handler and not allow null
- [x] `Membership.old_project` should be removed
- [x] `ProjectRelatedLink.project` should use the `models.CASCADE` deletion handler and not allow null
- [x] `ProjectRelatedLink.old_project` should be removed
# Events
- [x] `OldEvent` should be removed
# Blog
- [x] `OldBlogPost` should be removed
# Resources
- [x] `DateRange` should be moved to pages app
- ~delete everything else, including the entire app~

**Comment by rlskoeser** [comment]
cleanup migration ran in qa without problems and did not introduce any data errors
