### ISSUE TITLE
As an admin, I want user information and titles automatically populated so I don't have to manually enter it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#29]
If people log in with CAS or we use a script to create their account, here is the information that should be populated:

- basic user information: username, email, first and last name
- people section, people list: more information under the 'profile' section. Title set from the person's display name; a slug based on the display name is autogenerated for use in the url; it also pulls in phone number and office location if available (currently has a small bug where it's pulling in "[]" for people without that).
- If you go to the people / title list, job titles are created based on the imported person's job title in the directory, although they will have to be manually associated with people so you can add dates.

**Comment by rgmunson** [comment]
Checked with multiple people's information. Some people had auto-populated offices and phone numbers and others didn't but those people who didn't have offices or phone numbers also didn't have them in the campus directory. (So, whatever is in the campus directory is pulled in automatically.) Positions need to be manually associated so it's not a bug that they don't automatically appear.

Would have been helpful to know what to cross-check the data against the campus directory. Document where where info is being pulled from.
