### ISSUE TITLE
Support embedding Media Central content via oEmbed

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#305]
# testing notes
You should now be able to embed videos from Media Central in the same way that you'd embed something from YouTube: copy the URL into Wagtail's "embed" block. Any video on Media Central should work; you want to copy the URL that's in the URL bar when you view it. For example: https://mediacentral.princeton.edu/media/Center%20for%20Digital%20Humanities%20Overview/0_mnz807tm

You can test #273 as part of this issue too, since embedding a video using the new method should make it resize properly on mobile devices. After you add a video to the page, try resizing your screen to make it smaller and watch the video resize appropriately.

Note that this won't automatically fix the videos that are currently embedded on the site. For that, we have [an Asana task](https://app.asana.com/0/1134940917892680/1200660870137563/f) to track the work that's needed.

# dev notes
**Is your feature request related to a problem? Please describe.**
The homepage has a prominently displayed video hosted on Media Central that currently can't be represented in Wagtail because there's no embeddable version of that video, so it's stored as "migrated" html with an iFrame and will break if edited in Wagtail.

**Describe the solution you'd like**
Write a custom embed handler for content hosted on [MediaSpace](https://sru.mediaspace.kaltura.com/) that uses the Kaltura player.

**Additional context**
Some docs that might be helpful: https://knowledge.kaltura.com/help/mediaspace-oembed-integration

**Comment by thatbudakguy** [comment]
[list of iframes that need migrating](https://cdhprinceton.slack.com/files/U2VGMNE8P/F01SRDT9TJP/cdhweb-iframes.txt), most of which are media central videos

**Comment by thatbudakguy** [comment]
shifting to a 1 since this turned out to not need tests, and only a bit of regex writing/checking.

**Comment by cvansant** [comment]
1) When I embedded the video, the url in the bar in my browser didn't work (error messages: "The page could not be saved due to validation errors" and "Cannot find an embed for this URL"). Rather, it was the url in the "oEmbed" bar on Media Centralthat worked. Maybe that's what's intended, but wanted to check!

2) Video is resizing appropriately as I make my browser box (is that a term?) smaller and larger!

**Comment by thatbudakguy** [comment]
@cvansant hmm, thanks for testing. can you share the URL that you tried? both the oEmbed URL and the regular one from the URL bar should work (although only on the video's detail page).

**Comment by cvansant** [comment]
@thatbudakguy I tried the How We Work Video on Media Central. This link (https://mediacentral.princeton.edu/media/How+We+WorkA+The+Postdoc+Experience+with+Jim+Casey+and+Zoe+LeBlanc/1_53drqtu3/192064963) doesn't work. This link (https://mediacentral.princeton.edu/id/1_53drqtu3?width=608&height=402&playerId=25624581) does.

**Comment by thatbudakguy** [comment]
hmm, I just compared the URLs and noticed that the one you shared has a string of numbers at the end (`192064963`). i've no idea why Media Central does this — if you delete the numbers from the URL, you get the same page, and _that_ URL is embeddable. likewise, if you check the option "link to media page" in the "share" menu, you get the version without the extra numbers. I tried to make the extra numbers version work, but it appears their oEmbed endpoint doesn't support it!

So, I guess I need to amend those instructions: you can copy the "link to media page" URL or the "oEmbed" URL under "share", but not (always) the URL to the page itself. Kinda silly, but thanks for helping investigate this. I'll add some help text that should be visible when you create an embed.

**Comment by thatbudakguy** [comment]
@cvansant if you can confirm that:
- the oEmbed URL works for embedding
- the "link to media page" URL (the one without the numbers) works for embedding
then go ahead and close this.
