### ISSUE TITLE
500 error trying to add two speakers to an event

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#312]
## testing notes
In wagtail, open an event for editing with two or more speakers; try to preview and/or publish the event.

---

**Describe the bug**
Used wagtail to add two speakers to an existing event that did not previously have any speakers. Got a 500 error on both preview and published versions. Weirdly, it worked fine with a single speaker, and other events with multiple speakers render correctly (although I haven't tested editing them).
 
**Additional context**
Error email generated by django reports:

> 'Speaker' object has no attribute 'person__first_name'

It looks like it's triggered in the modelcluster sorting on form save

**Comment by thatbudakguy** [comment]
tried both preview and published functionality with multiple speakers; works correctly. the display/spacing of speaker's names on the event detail page for more than one speaker looks a little weird (maybe a comma-separated list would be better?) but this issue can be closed.
