### ISSUE TITLE
migrated rich text content loses links and formatting when edited, has spaces added from exodus migration

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#316]
- [x] fix richtext editor feature list
- [x] script to cleanup formatting

**Comment by rlskoeser** [comment]
@manawinters do you have time to help review this one on the test site? It should be easier to edit migrated content now — the block supports links and other elements, and I ran a script to clean up the extra spaces that were introduced in the exodus migration to wagtail.  You could poke around and look at pages on the public site and in wagtail to see if things look ok and nothing looks broken by my cleanup script, and try editing a little bit of the migrated content.

**Comment by manawinters** [comment]
@rlskoeser , can you suggest a specific page to look at? I was thinking of the Mukurtu event (and adding the video), but you edited already.

**Comment by rlskoeser** [comment]
@manawinters the home page has video embedded and lots of links, if you want to experiment with that one

**Comment by rlskoeser** [comment]
Several pages modified by the script reviewed by RSK and Mana and everything looks ok — extra whitespaces are gone now, links are editable in wagtail admin. 

I also reviewed some of the pages with embedded content from our other report and was able to confirm that this cleaning script did not disrupt the embedded content.
