### ISSUE TITLE
Add explicit ordering for Page-derived models

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#318]
# testing notes
- create a new blog post and feature it and check that it appears first on the homepage carousel
- visit the admin list page for blog posts, projects, events, and profiles and check that all of them are ordered in a reasonable way (start time for events, title for profiles and projects, first publication date for blog posts)
# dev notes
**Describe the bug**
Because [models derived from wagtail `Page` can't have a default `Meta` ordering](https://docs.wagtail.io/en/stable/topics/pages.html#page-queryset-ordering), they need to have methods that handle ordering defined on their `QuerySet` and called in every place that ordering is needed. One place it's currently not being used is on the display of featured posts on the homepage:

https://github.com/Princeton-CDH/cdh-web/blob/74cc6f30e21bf12fba47ad0f44c84410f18e3071/cdhweb/pages/models.py#L242-L246

We need to call `recent()` here to preserve the ordering, otherwise newer featured posts won't show because there are too many and we only want 6.

Relatedly, all these models that are managed through wagtail `ModelAdmin` instances (i.e. `Event`, `Profile`, `BlogPost`, and `Project`) should explicitly define `ordering` in their `wagtail_hooks.py`. Otherwise, the ordering may be unpredictable, as reported by kavita.

**Comment by rlskoeser** [comment]
The test blog post I created is now showing up first in wagtail admin (was not before this change was deployed), and is now showing up in the featured carousel on the home page.

Sort order in wagtail for blog posts, projects, events, and profiles all look good (glad to see default sort is clearly highlighted).
