### ISSUE TITLE
short description for blog posts are not editable in wagtail

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#327]
**Describe the bug**
Can't override the short text displayed for blog post preview

**Expected behavior**
Formatted description should be included in wagtail content panels

**Comment by thatbudakguy** [comment]
added to admin editable fields and confirmed this is working. it looks like `search_description` will also be set to this field when it's set, which seems like reasonable behavior rather than the reverse.

**Comment by rlskoeser** [comment]
Confirmed in qa that the description field is available in wagtail now. Setting content populated the preview text on the updates list and in the homepage carousel.
