### ISSUE TITLE
As an admin, I want to create and edit grant types and associate grants with projects, so that I can document when and which kinds of grants a project received from CDH.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#33]

**Comment by rgmunson** [comment]
Created several grant types which I added from the dashboard. Created a new project and associated preloaded grant type with it. Edited an existing project and changed the grant type. Changed the dates for the duration of the grant. All worked. 

One thing to consider is what we do with projects that receive multiple grants from us; do they get a page for each year? Currently, I've entered the two grants on the same year (for MEP) but it looks like that might mess up the filtering function. (I will copy this onto the Git issue for filtering.)

**Comment by rlskoeser** [comment]
@rgmunson the grant history is a new feature, so we'll have to think about how and if we want to display it on the public site.  Maybe a project history page that displays different grants and contributors?

**Comment by rgmunson** [comment]
I like the idea of having a "project history" section! I wasn't sure if I should put this comment anywhere else since I didn't see a feature for grant history/filtering. Ok to leave here or should it become its own issue?

**Comment by rlskoeser** [comment]
@rgmunson let's add it to the feature list in asana so it can be prioritized against other ideas.
