### ISSUE TITLE
As an editor I want to see accessibility checks when I'm logged in or previewing a page so that I will be alerted if something is causing accessibility problems and have guidance about how to fix it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#347]
## testing notes

- [x] login to wagtail, open a page for editing, then view the preview; in the bottom right corner you should see an editoria11y panel (see [editoria11y site](https://github.com/itmaybejj/editoria11y) for an example); it should open in "assertive mode", meaning the panel should be open and warning you about anything that's problematic
- [x] go to the public site and stay logged in: you should see the editoria11y panel in the bottom right corner, but it should be in "polite" mode (you have to click to open the panel); also, it should not overlap with the wagtail userbar menu
- [x] test the public site as a user who is not logged in: confirm you don't see the editoria11y panel

**Is your feature request related to a problem? Please describe.**
Not all of our content editors have accessibility training and don't know how to make web content accessible.

**Describe the solution you'd like**
Integrate [Editoria11y](https://github.com/itmaybejj/editoria11y) so logged in editors see the checks on regular pages and in particular when they are previewing a page in wagtail.

**Comment by rlskoeser** [comment]
preliminary integration in #348 

still to do:
- determine whether we should keep vendor copies of editoria11y js & css locally or pull current released versions from editoria11y
- fix placement of the menu: currently it conflicts with the wagtail userbar button. I see that it's positioned with css, but want to determine the best way to adjust the location so we won't have problems pulling in updates to the styles
![Screen Shot 2021-07-15 at 4 10 44 PM](https://user-images.githubusercontent.com/691231/125851608-0a7432ad-491a-49a9-8200-149a8614516c.png)
- set `ed11yAlertMode` to assertive when viewing a page preview so any errors will be more noticeable (have draft code for this but it isn't working and not sure this is the best approach)
- configure `ed11yCheckRoot` to restrict checks to main content

**Comment by itmaybejj** [comment]
Regarding moving the toggle -- no issues with overriding it via CSS. set whatever right/bottom you want:
`#ed11y-panel {
    right: ##px !important;
    bottom: ##px !important;
}`

With ed11yAlertMode -- yes, that's what I recommend. The Drupal integration has a "smart" config option that hands off a last-changed timestamp to the client, and the client runs assertively on recently changed content and politely on older content. I went that route because our reverse-proxy caching made it problematic to have the server make the decision ("aggressive" ended up getting cached). [Relevant goodies around line 28.](https://git.drupalcode.org/project/editoria11y/-/blob/1.0.6/js/editoria11y-drupal.js)

**Comment by cvansant** [comment]
It seems as if the assertive mode box only comes up if a problem is identified. For instance, a box comes up with the summer fellows page, but no box comes up with humanities data teaching fellows (the latter seemingly has no issues). But I see the difference between the two modes, so I'm guessing that's right! Moreover, I think assertive mode only comes up the first time I open the preview page. When I've returned to the same preview page, assertive mode doesn't come up.

And by public site, I'm assuming you mean the test site, not the actual public site, right (cdh.princeton.edu)?

**Comment by rlskoeser** [comment]
@cvansant yes, that's all correct! In assertive mode, the box will only be open if there's a problem  that needs to be addressed. I don't know about it only showing up the first time you preview something ... maybe it only happens on page load, or something.

And yes, by public site I mean the publicly accessible part of the test site!
