### ISSUE TITLE
As an admin, I want to associate urls for other resources with projects so that I can provide links to materials related to projects.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#35]
## Notes for testing
- currently only website url is displayed on project detail page (other items have not been incorporated into the design yet)

- e.g., project website url, twitter, etc

See #36 for editing resource types.

**Comment by mnaydan** [comment]
Was able to add URL to a project via "Projects" > "Project resources" in admin. Successfully displays on project page (but in bright hyperlink blue). Problem: Clicking on it on test site brings up a 404 page. 
<img width="916" alt="screen shot 2017-08-31 at 3 23 33 pm" src="https://user-images.githubusercontent.com/22945600/29942018-686085fa-8e62-11e7-9762-3524bb30c334.png">

**Comment by mnaydan** [comment]
Was able to add URLs via project resources. As you said, only Project Website displayed on project detail page. Link worked now. Maybe add option in admin for target=blank.
