### ISSUE TITLE
As a Content Editor, I want existing page links to resolve after I rename or move a page so that I don't have to manually create a redirect.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#354]
# testing notes
There are two different behaviors that should automatically trigger a redirect to be created:
1. moving a page. you can test this with any content page (for example, the "about" page) — if you move it to live underneath a different page, a redirect should be created so that you can still access it from the old URL, e.g. `/about` instead of `/engage/about` (if you moved it under "engage").
2. editing a page's slug. if you're editing the page in wagtail and check the "promote" tab, you can change the slug (the bit at the very end of the URL). as with above, you should still be able to access it at the old URL, which will redirect you to the new one.

Note that changing a page's title doesn't automatically change its URL or create any redirects! To do that, you need to edit the slug or move the page (the two things above).

# dev notes
see [wagtail recipe docs](https://docs.wagtail.io/en/stable/reference/pages/model_recipes.html#have-redirects-created-automatically-when-changing-page-slug)

**Comment by thatbudakguy** [comment]
bumping to a 2 since this involved a little more than the provided wagtail recipe

**Comment by rlskoeser** [comment]
> bumping to a 2 since this involved a little more than the provided wagtail recipe

makes sense; do you want to revise the issue/story also ? (rename or move?)

**Comment by cvansant** [comment]
1) This worked--I moved "jobs" from "engage" to research and the "engage" url still worked.
2) Also good! Changed the slug for seed grants from "seed-grants" to "seed-grant."
