### ISSUE TITLE
As a user, I want to access the site search via the main navigation so I can start a search from anywhere.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#359]
# testing notes
[Figma Designs](https://www.figma.com/file/7P52LnAjsL24HeeJmPChy2/?node-id=44%3A83)

You should now be able to begin your search from any page!
* click the magnifying glass in the top right to start a search.
* you should immediately be able to type into the search box. 
* hitting enter will send you to the search page (#19).
* clicking the "X" will cancel your search and close the bar.

Test the look and behavior of the search bar on both desktop and mobile and note anything that doesn't make sense.

# dev notes

our inspiration for this UX is the main https://www.princeton.edu/ site and its expanding search bar.
see also #19 

- <s> re-add or adapt command to populate site menu so percy previews are more accurate</s> (postpone)
- <s> post a video of the animation for the search bar opening to the PR </s> (postpone)
- [x] test search bar open/close states via percy

**Comment by cvansant** [comment]
I see the x to close the bar on the homepage, but I don't see it on the search page.

**Comment by cvansant** [comment]
I see the x to close the bar on the homepage, but I don't see it on the search page. One thing I also noticed is that the search bar disappears when you scroll down far enough. I don't know if that's a big deal but it happens.
