### ISSUE TITLE
As an admin I want to edit and create resource types so I can determine what kind of links and resources can be associated with people and projects.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#36]
# Notes for testing:
- a few resource types will be pre-populated
- sort order displayed and editable on the list view (eventually this will be used to determine sort order in public display site; later we plan to make sort order drag & drop here and elsewhere in the admin site)

**Comment by mnaydan** [comment]
Was able to add, delete, edit, and reorder resource types in admin.
