### ISSUE TITLE
semantic heading hierarchy problem on project pages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#362]
**Describe the bug**
editoria11y is flagging out of order headings on the project pages, and it is correct — project title is `h1` and every role title is an `h3`. (I don't remember why we did this, it doesn't seem very logical — should they be headings at all? should we have screen-reader only labels to indicate this is a list of project contributors?)

**Screenshots**

![Screen Shot 2021-08-04 at 1 10 02 PM](https://user-images.githubusercontent.com/691231/128240396-dc2966dc-bc10-4671-bb17-fe0b140ff9df.png)

**Additional context**
Probably out of scope for this fix, but it would be nice to revisit our project alumni handling, especially for long-running projects with large teams.  I don't love how it lumps everyone together with no indication of their role or when they were involved.

**Comment by thatbudakguy** [comment]
what do you think about making this a `<dl>`, maybe?

**Comment by rlskoeser** [comment]
@thatbudakguy yes, I wondered about that! Seems like it would be more semantic
