### ISSUE TITLE
invalid heading levels on event page

### ISSUE THREAD

**Issue by manawinters** [Princeton-CDH/cdh-web#378]
When I preview a new Event, I receive an error message, "Heading jumped from level 1 to 3" in the Project Managers section. I cannot directly edit the names as they are automatically generated.

<img width="1168" alt="Screen Shot 2021-08-25 at 12 09 06 PM" src="https://user-images.githubusercontent.com/79113717/130826350-d4216245-17cc-4697-99d0-6a9488a3ca64.png">

**Comment by rlskoeser** [comment]
looks like a similar problem to #362  (still not sure how this happened, did project and event titles used to be h2s? 🤯 )

**Comment by rlskoeser** [comment]
confirmed resolution in qa
