### ISSUE TITLE
As a content editor, I want to create and edit event locations so that I can enter them once and have them displayed consistently across the site.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#38]
## Notes for testing
- CDH should be automatically preloaded

**Comment by rgmunson** [comment]
CDH was preloaded; was able to add location from dashboard. It does then display consistently across the site (and is preloaded for new events). To experiment, I didn't give it a short name. Without a short name it's not possible to select it to edit from the "locations" page, which seems like a bug so I'm not closing the ticket yet.

**Comment by rlskoeser** [comment]
@rgmunson good catch!

**Comment by mnaydan** [comment]
CDH was preloaded. Was able to add location from dashboard and it displays consistently and is preloaded for new events. Works with and without short name now.
