### ISSUE TITLE
Homepage does not display correctly on Safari.

### ISSUE THREAD

**Issue by cvansant** [Princeton-CDH/cdh-web#380]
I'm using Safari 13.1.2 (Catalina 10.15.6), and having trouble with two images on the homepage. You'll see first that "people" is too close to the CDH logo, and that RM's photo covers up the consultations link.
![Screen Shot 2021-08-26 at 9 26 16 PM](https://user-images.githubusercontent.com/60949427/131190262-d0e8f191-d743-4f93-b179-27f1a4ea615b.png)
![Screen Shot 2021-08-26 at 9 27 42 PM](https://user-images.githubusercontent.com/60949427/131190285-838bfddc-3ded-452b-b0b6-6f38075659f9.png)

**Comment by rlskoeser** [comment]
@cvansant is this still a problem? Can't replicate this with current Safari on my laptop (which is a newer version); I also used responsive mode in Safari to check #381 and couldn't see that problem either

**Comment by cvansant** [comment]
@rlskoeser Looks fine now.
