### ISSUE TITLE
Event cards showing up out of order

### ISSUE THREAD

**Issue by manawinters** [Princeton-CDH/cdh-web#384]
Event cards are showing up out of chronological order

<img width="1277" alt="Screen Shot 2021-09-22 at 10 00 43 AM" src="https://user-images.githubusercontent.com/79113717/134358290-8895d3ec-f3b2-46d4-98b5-1359fa2e3a4e.png">

## Testing Notes

https://test-web.cdh.princeton.edu/events/

- [x] Confirm that updated ordering looks as expected.
- [x] Create a new event, ensure that it is sorted correctly in "upcoming events" section

## dev notes

`upcoming` method on `EventQuerySet` needs the `order_by` specified because wagtail pages don't get default ordering. Should match the sort in the `recent` method.

**Comment by rlskoeser** [comment]
order on the home page and upcoming events was fixed, but not individual months

**Comment by rlskoeser** [comment]
confirmed correct sorting on test site
