### ISSUE TITLE
Cannot add standard page under "Events"

### ISSUE THREAD

**Issue by cvansant** [Princeton-CDH/cdh-web#391]
I want to add a page under "events" that includes a description of a whole series of events. We have done something similar in the past with Douglass Day and the Collections as Data Series, back before Wagtail. However, with Wagtail, I am only able to add event cards under "Events."

**To reproduce**
1. On Wagtail, go to Events and then "+ child page." The only option is to create an event card.
2. Alternatively, go to Home and then "+ child page." Add a page for the series. Then, under "more," click "move." Unfortunately,  I am unable to move the page to Events.

**Expected behavior**
I would like to create a page and move it to Events, or to have the option directly to add a child page for an event series under Events.

**Device information**
 - macOS Catalina 10.15.7 (I'm using Chrome)

## dev notes

Revise events list page definition to allow it to have content pages as children; update existing unit tests checking allowed child behavior

**Comment by rlskoeser** [comment]
I revised the events link page to allow content pages as well as event pages, but it doesn't seem to be doing what we hoped. (The allowed child page unit test was also failing, so I disabled it because I thought it was a fluke, but maybe it isn't registering properly or it's being overridden somewhere else.)

**Comment by rlskoeser** [comment]
@cvansant I think I found the problem, please retest at your convenience.

**Comment by cvansant** [comment]
This worked! Now I want to have event cards work as child pages under the  new content pages for the event series, but that's an issue for another day.
