### ISSUE TITLE
Humanities + Data Science Institute Instructors do not appear on the affiliates page.

### ISSUE THREAD

**Issue by cvansant** [Princeton-CDH/cdh-web#399]
**Describe the bug**
Humanities + Data Science Institute Instructors do not appear on the CDH affiliates page even though they have an affiliation with the CDH. They have been entered as people in Wagtail and the position "Humanities + Data Science Institute Instructor" has been created.

**Expected behavior**
I would like to see David Kinney and Amy Winecoff show up on the affiliates page, with the label "Humanities + Data Science Institute Instructor." https://cdh.princeton.edu/people/affiliates/

Moreover, in the future, I would like those who participate in the Humanities + Data Science Institute to appear as "Humanities + Data Science Institute Participant" on either the affiliates or the students page, as appropriate.

**Comment by rlskoeser** [comment]
@cvansant I have made a small change that I hope is sufficient for this. Could you test with the new titles on the test site to confirm if it works as desired?

**Comment by rlskoeser** [comment]
closing based on slack conversation with @cvansant after testing and discussing limitations; should be sufficient for current needs
