### ISSUE TITLE
As an admin, I want to create and manage landing pages and other content pages so that I can publish top-level and other content pages.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#4]
As an admin user, I want to be able to create and manage content pages that will use templates for landing page and content page styles so that I can arrange and publish content.

- [x] add page setup functionality to Mezzanine
- [x] create templates for landing pages w/ full-bleed image
- ~customize template for generic content pages~

**Comment by rlskoeser** [comment]
@bwhicks what was it you thought wasn't complete here with regard to page setup functionality in mezzanine?

**Comment by bwhicks** [comment]
@rlskoeser I *think* I meant to click the top two and not the bottom (content pages) but fumbled it while writing the story, and flipped them. I know the full bleed pages were more or less done, but I didn't believe we'd worked out the pattern for content pages and their editing fully. It's definitely in progress.

**Comment by rlskoeser** [comment]
@bwhicks ok, thanks for explaining.  I thought the landing page functionality was done, which was why I was confused.  Might worth splitting out so we can test landing pages sooner.

**Comment by norabenedict** [comment]
As a whole everything works well with adding landing and content pages. The only slight problems are the semi-broken images, but this does not affect the addition of landing and content pages -- this is only a surface visual and does not change the goal, which is met!
