### ISSUE TITLE
website link isn't used on person list pages if person has an unpublished profile page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#405]
**Describe the bug**
People with unpublished profile pages and website urls don't have any link on person list pages

**To reproduce**
1. Create a person record with a website url and a published profile page
2. Unpublish the profile page
3. Go to the affiliates page where the person is listed
4. The person card does not link to their website url

**Expected behavior**
The person card should link to the person's website (if available) when the profile page is unpublished.

**Comment by cvansant** [comment]
@rlskoeser Looks good! I checked to make sure Brigid Doherty's profile is unpublished and that the link to her dept site is on the wagtail people page. I then checked the affiliates page and her photo linked to her dept page as expected. Thank you!
