### ISSUE TITLE
update 404 and 500 error page images

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#422]
## testing instructions
please review the updated 404 and 500 error pages and let me know any concerns

- [404](https://test-web.cdh.princeton.edu/_404/)
- [500](https://test-web.cdh.princeton.edu/_500/)

**Comment by cvansant** [comment]
Quick question: With the 404 page, I can still see all the menu items at the top of the page. With the 500 page, I can't. Is that normal?
![Screen Shot 2023-08-30 at 8 59 45 PM](https://github.com/Princeton-CDH/cdh-web/assets/60949427/6d69d78b-6b49-4a41-84d2-beb8d44f477d)

![Screen Shot 2023-08-30 at 9 00 31 PM](https://github.com/Princeton-CDH/cdh-web/assets/60949427/856cdd65-08da-4c2b-a67f-993c53fbd8f8)

**Comment by rlskoeser** [comment]
@cvansant very observant! Yes, that is expected behavior - a 500 error means something unexpected went wrong, and you don't want to run the risk of anything else going wrong when you serve out the error page, so it's intentional simplified and omits the logic for generating the menus.

**Comment by cvansant** [comment]
@rlskoeser Also noting that it has the "subscribe to the newsletter" button and the menu items at the bottom of the page. As long as that's okay, I think they look fine!

**Comment by rlskoeser** [comment]
thanks @cvansant !
