### ISSUE TITLE
project thumbnails don't display on project card if project doesn't have a larger image associated

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#424]
reported by @cvansant on slack

**Comment by rlskoeser** [comment]
@cvansant I copied production data to the test site and looked again at the template code and found the line where it's checking for the main image instead of the thumbnail. It's corrected now on the test site. Do you want to confirm?

**Comment by cvansant** [comment]
Looks good! Thank you!
