### ISSUE TITLE
Landing page - banner image

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#45]
<img width="1354" alt="screen shot 2017-09-19 at 4 19 20 pm" src="https://user-images.githubusercontent.com/17734456/30613500-545d1c96-9d56-11e7-9206-4bb4c92833e8.png">

- banner image goes all the way to he top (there are area of overlap) so there won't be space between image and the navigation bar
- banner image aligns center when resizing the window (might be a away to borrow the code from Derrida? same behavior)

**Comment by rlskoeser** [comment]
It was an interaction between the background setting and the fall-back gradient color!  Looks better now, thanks for catching this.
