### ISSUE TITLE
Background color - blog and text page 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#46]
light grey is used on pages with cards, such as home, projects, people... blog and individual project page, staff page, has white background.

**Comment by xinyil** [comment]
Sorry if I missed this: landing page also has grey background because the text are on white large "card"

**Comment by rlskoeser** [comment]
No, I hadn't realized the landing page was a "card".  Fixed so it acts like a card in LM but not in S.
