### ISSUE TITLE
Navigation - hide the divider line when not displaying secondary menu 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#47]
<img width="1048" alt="screen shot 2017-09-19 at 4 29 22 pm" src="https://user-images.githubusercontent.com/17734456/30613950-dd19452c-9d57-11e7-80a3-1a7a7fa646e3.png">

**Comment by xinyil** [comment]
![screen shot 2017-09-25 at 10 45 06 am](https://user-images.githubusercontent.com/17734456/30814604-a16dc09e-a1de-11e7-8650-1eb058798612.png)

- the highlight bar is getting into the divider line
- can we make the rollover status the same as the expanded active status, i.e. displaying secondary menu and highlight

**Comment by rlskoeser** [comment]
Fixed the highlight bar.

Making rollover status same as active status would make it _much_ easier to navigate the site, but we need to restructure the html and styles to handle that.  Let's make a separate issue for that.

Restructuring the html to include non-active menus will also make it easier to generate a better mobile nav.
