### ISSUE TITLE
As a user, I want to subscribe to a blog post feed so I can read CDH updates in the feed reader of my choosing.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#51]
## Notes for testing
- Provides both RSS and Atom feeds.  Should be linked at the bottom of blog index and blog detail pages and also included in the header for autodiscovery.
- Easiest way to test is probably to install a browser RSS tool like [chrome rss extension](https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd?hl=en) which will show the auto-discover url and also give you a nice preview of the content.

**Comment by rgmunson** [comment]
I installed the Chrome extension and used both subscribe buttons worked perfectly with it.
