### ISSUE TITLE
As a user, I want to view previous blog posts by year and month so that I can read past updates.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#52]

**Comment by jabauer** [comment]
Dropdown list and month links work.
When the dropdown list is first activated on the top level Updates page it sorts in chronological order (earliest first).  Once you have used the drop down list to check out a particular month, it then resorts itself to reverse chronological order (latest first).  It should always display as the later.

**Comment by jabauer** [comment]
List links still work.
List is now always sorted in the right order.
