### ISSUE TITLE
Add robots.txt with link to sitemap

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#53]
I like option 2 suggested here:
http://fredericiana.com/2010/06/09/three-ways-to-add-a-robots-txt-to-your-django-project/

We should probably also add the favicon the same way.

**Comment by bwhicks** [comment]
Accidentally linked commits for initial setup to #52, noting here for posterity that I cannot count.

**Comment by rlskoeser** [comment]
This is working; I don't think we need acceptance testing on it.
