### ISSUE TITLE
Typography - link style 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#55]
![screen shot 2017-09-25 at 10 57 54 am](https://user-images.githubusercontent.com/17734456/30815188-6738935c-a1e0-11e7-8f7e-cec0692e2f81.png)

- link style in blog is getting double underline
- we would keep the blue underline and use Brown for inline link

**Comment by rlskoeser** [comment]
Cleaned up the extra underlines in content in production and on this blog post on the test site so you can check.  Set inline link font to use Brown font.

**Comment by xinyil** [comment]
inline link is 18px, slightly smaller than 20px Lyon so the x-height match!

**Comment by xinyil** [comment]
underline looks a bit too close to the text, try make the underline perhaps 0.1 em further away form the text?

**Comment by xinyil** [comment]
I forgot we have smaller text size for small viewport! Link style for S should also be smaller, 14px
<img width="294" alt="screen shot 2017-09-27 at 12 53 38 pm" src="https://user-images.githubusercontent.com/17734456/30926378-e759eac4-a382-11e7-85a2-a30fd113f610.png">

**Comment by rlskoeser** [comment]
Adjusted link text size for small viewport
