### ISSUE TITLE
Event card

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#56]
![screen shot 2017-09-25 at 11 01 51 am](https://user-images.githubusercontent.com/17734456/30816608-68baeb0e-a1e4-11e7-8c5e-dc6830c72797.png)

- Do we have a presenter/instructor field?

- The date and time on one the cards is black, different from all the others.
- use en dash for time intervals (how to type: option+hypen)

**Comment by rlskoeser** [comment]
I think I've got everything except for the random cards with black text instead of grey.

**Comment by xinyil** [comment]
<img width="1088" alt="screen shot 2017-09-26 at 1 01 40 pm" src="https://user-images.githubusercontent.com/17734456/30873565-aa5a2b38-a2bb-11e7-87ad-41555062e54a.png">

The event type labels are original a vector, but it's good to have the flexibility to edit it!
Use bold and padding to resemble it closer.

I didn't reproduce the black type issue.

**Comment by rlskoeser** [comment]
@xinyil wonderful, thanks! I couldn't tell for sure which font it was and guessed on the sizes, I'll update.

**Comment by xinyil** [comment]
<img width="348" alt="screen shot 2017-09-27 at 12 41 13 pm" src="https://user-images.githubusercontent.com/17734456/30925873-5b7779fa-a381-11e7-84d3-f3f0c6bf5de4.png">

add right padding for event titles

**Comment by xinyil** [comment]
<img width="351" alt="screen shot 2018-02-23 at 3 10 27 pm" src="https://user-images.githubusercontent.com/17734456/36614753-b6c412e2-18ab-11e8-8425-d873b32f3dfa.png">
<img width="379" alt="screen shot 2018-02-23 at 3 10 22 pm" src="https://user-images.githubusercontent.com/17734456/36614754-b6d4e1a8-18ab-11e8-8672-da7b45d24c88.png">
notice how the box size of the div and the span is different
the div is 15px away form the botton, but with the extra space the date line looks further away from the buttom than the rest of the margin between text and white card edge

**Comment by rlskoeser** [comment]
@xinyil I don't understand what you want me to change on this one. The design has a 20px space between the date and the time

**Comment by xinyil** [comment]
@rlskoeser it should be 15px space, same as all the other space between text and card edge

**Comment by xinyil** [comment]
<img width="1112" alt="screen shot 2018-02-23 at 4 53 16 pm" src="https://user-images.githubusercontent.com/17734456/36618714-31a7c932-18ba-11e8-9a8f-bfb2b8c8f5b3.png">
doesn't seem to be fixed. see the image for an example when I chaneged the div height from 25px to 19px.

**Comment by rlskoeser** [comment]
@xinyil ah, I see - you're talking about the space between the text and the bottom of the card.  I think you may be asking for more precision than is reasonable for web design here.  I have margin and padding set to zero on both divs, so I'm not sure where the extra space is coming from.  I thought maybe it was an issue about the text not being vertically-aligned to the bottom (which is a little difficult with css), but I tinkered with that and it didn't make much difference.  I think we might be able to control this with line-height - do you want to suggest a value?

**Comment by xinyil** [comment]
1. I tried to make line hight to 1, and add 5px spacing between the event title and the speaker. 
2. another other way is to change the div height to 19px

<img width="764" alt="screen shot 2018-03-02 at 1 37 16 pm" src="https://user-images.githubusercontent.com/17734456/36915530-12903074-1e1f-11e8-9563-a9fc265e614f.png">

<img width="1323" alt="screen shot 2018-03-02 at 1 34 32 pm" src="https://user-images.githubusercontent.com/17734456/36915535-140f2c5c-1e1f-11e8-9315-d279d6f8be45.png">


I'll defer to you to decide which way is better!

**Comment by thatbudakguy** [comment]
`line-height: 1;` brought it up a hair further, so I think that's probably what we wanted (makes more sense than setting it to a px value).

closing this as I don't think it merits spending more time on.
