### ISSUE TITLE
Staff card

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#58]
![screen shot 2017-09-25 at 11 48 09 am](https://user-images.githubusercontent.com/17734456/30817801-e08739d2-a1e7-11e7-9e39-6174aece78c7.png)

**Comment by rlskoeser** [comment]
Loaded one profile thumbnail in test so you can check the updates.

**Comment by xinyil** [comment]
<img width="1186" alt="screen shot 2017-09-26 at 1 20 08 pm" src="https://user-images.githubusercontent.com/17734456/30874218-ae6b4af2-a2bd-11e7-8d8a-c9b8b9b22614.png">
<img width="1182" alt="screen shot 2017-09-26 at 1 21 37 pm" src="https://user-images.githubusercontent.com/17734456/30874221-b1764f4e-a2bd-11e7-943e-1e568ea0cbd6.png">

I think the extra space between lines are caused by inherited line height, and quick fix in attached screenshot. Might not be the best way just to demo.
