### ISSUE TITLE
Footer - S -spacing and cursor 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#59]
![screen shot 2017-09-25 at 12 04 55 pm](https://user-images.githubusercontent.com/17734456/30818673-3b01efa4-a1ea-11e7-83ad-94b3662b8172.png)

**Comment by xinyil** [comment]
Can we make the area between text and plus sign also clickable?
Sorry I wasn't clear before – I missed this in the design as well – apple recommended a min size of 44px for touchable elements. Let's make the height of an unexpanded block 44.

**Comment by xinyil** [comment]
align text to the center between lines, vertically

**Comment by thatbudakguy** [comment]
These look accurately spaced to me, and are clickable.
