### ISSUE TITLE
As an admin, I want to manage links in the footer so I can update site navigation when content changes.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#6]
## Notes for testing
- Updated 9/19/2017 with revised styles.  Both desktop and mobile footer styes working; layout is based on expected content and presence of submenus.

**Comment by mnaydan** [comment]
Was able to add a page to appear in both header and footer. Was able to add a page to appear in footer only. Problem: reordering pages in Mezzanine affects order in both header and footer. If a page is set to appear in the header but not the footer, the footer leaves a blank space where the page would be. Additional problem: adding 3+ footers causes the subscribe footer to run into the address footer.
<img width="1066" alt="screen shot 2017-08-31 at 2 26 36 pm" src="https://user-images.githubusercontent.com/22945600/29939004-7b34e482-8e58-11e7-9833-7c14535d99d3.png">

**Comment by rlskoeser** [comment]
@mnaydan this is great feedback.  I think it is ok - and logical - that header order and footer order match.  There may be some constraints in the design that impact the number of items we can display, but we should set it up to be as flexible and user-editable as possible.  Let's kick this one back for more development work.

**Comment by rgmunson** [comment]
I was able to add pages to appear in both the header and footer and to edit existing pages to make them appear only in the header, only in the footer, or in both. The trouble with the header that Mary spotted appears to be fixed. I'm wondering if there is a similar spacing issue going on with the footer. If there are more than 5 pages added to the footer (5 being the number that will fit in the far left navigation) a new column begins but the spacing is odd. We may just want to limit the number of pages in the footer to 5? 
<img width="1027" alt="screen shot 2017-09-19 at 2 37 23 pm" src="https://user-images.githubusercontent.com/20585637/30609192-b5dc9f68-9d48-11e7-865d-4b6b4f58f541.png">

**Comment by rlskoeser** [comment]
I'm going to call this good enough - the design is pretty specific to the content we (expect to) have, but I think that's ok at this point.
