### ISSUE TITLE
Navigation - S

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#60]
![screen shot 2017-09-25 at 12 12 44 pm](https://user-images.githubusercontent.com/17734456/30818934-08158e60-a1eb-11e7-83f9-d900a1773070.png)

- Can we in the same way as the footer? Type size are the same with nav in L and M. 
- Also increase spacing between text and lines to ensure easier touch (noted in another footer issue).

- the hamburger button should change to close button when the menu is expanded. CDH web can share these icons for derrida.

- CDH logo doesn't fit well in the small navigation. Maybe center it?

**Comment by rlskoeser** [comment]
@xinyil I've changed this so the footer nav (which was already in good shape for mobile) is used as the main mobile nav as well.  Clicking the menu button triggers a style so the footer is displayed basically full-screen (roughly) over the page contents.

I couldn't find the menu / close icons in derrida, they seem to be svg but it's not clear where they are.  Do you have a copy somewhere?

There's now no CDH logo displayed on the menu - do you think that's ok?

**Comment by thatbudakguy** [comment]
Added a line to swap the hamburger icon with a close icon, but this looks good otherwise.
