### ISSUE TITLE
Resource links on user profile page don't work

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#63]
## Notes for testing
I've added resource links to Jean's page in production and test to make it easy to compare.

They are listed but with no url on the production site.

**Comment by rgmunson** [comment]
Resource links are working in the test site but not in production. (I went to Jean's page to test both times.) Looked at the admin for the test site and the user resources are set up correctly. Looked at the admin for the production site and saw that both resources use the GitHub link even though one of them is supposed to be the website. I fixed the resource URLs, associating them with the correct type, but returning to the production site after doing this reveals that the links are still not working.
