### ISSUE TITLE
Blog - quote and bold typography style 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#65]
<img width="1403" alt="screen shot 2017-09-26 at 1 32 15 pm" src="https://user-images.githubusercontent.com/17734456/30874792-623e43e4-a2bf-11e7-8d9e-73580ed181de.png">
- refer to zeppelin for italic full quote style
- somehow all the italics aren't displayed in lyon, neither does project subtitle on the project  thumbnail card. 

<img width="722" alt="screen shot 2017-09-26 at 1 31 42 pm" src="https://user-images.githubusercontent.com/17734456/30874769-53225c06-a2bf-11e7-9f75-d37d710f6de7.png">
in Safari (right), it seems like extra letter-spasing has been added by the browser, so the bolded text are loose. In general I think bolded inline text does't look good and they don't really stand out and serve the purpose. We might want a different b/em style.

**Comment by thatbudakguy** [comment]
Can't duplicate the bold spacing issue on safari, and it looks like our quote styles are now using Lyon with the correct spacing, so I'm going to close this.
