### ISSUE TITLE
Plain text page - use the same style as blog post 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#67]
Plain text pages, such as Postdoctoral Fellowships, would be in the same style as blog post 

current text block width is too wide
<img width="1229" alt="screen shot 2017-09-27 at 12 57 18 pm" src="https://user-images.githubusercontent.com/17734456/30926515-6a1f0e26-a383-11e7-8fef-2bf0121cbb38.png">

**Comment by xinyil** [comment]
it doesn't seem to be fixed?

**Comment by rlskoeser** [comment]
@xinyil hmm, no it doesn't. I customized the template and thought I had it working. 'll look again

**Comment by rlskoeser** [comment]
@xinyil check it again please

**Comment by xinyil** [comment]
the blog in LMS looks good, but the column style change is not reflected on text content pages.

**Comment by rlskoeser** [comment]
@xinyil can you check the column style on content pages again? It looks ok to me, so I'd like to know what I'm missing.

**Comment by thatbudakguy** [comment]
this looks done. I edited the styles slightly to make the top margin match the margins on a blog post, but horizontal spacing looks good.
