### ISSUE TITLE
Project page - excerpt and name style 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#68]
- excerpt excesses the grid 

![screen shot 2017-09-27 at 1 00 54 pm](https://user-images.githubusercontent.com/17734456/30926841-75a818cc-a384-11e7-88ab-2e859d2969b4.png)

<img width="628" alt="screen shot 2017-09-27 at 1 04 03 pm" src="https://user-images.githubusercontent.com/17734456/30926865-8c28c330-a384-11e7-8915-a643b1f5f332.png">

![screen shot 2017-09-27 at 1 01 17 pm](https://user-images.githubusercontent.com/17734456/30926867-9006ad1e-a384-11e7-9361-ccfd110df319.png)

**Comment by xinyil** [comment]
- the cut off issue have been fixed
- there're still a few typography issue: name should be 18px, the excerpt should be in Lyon italic 21px
<img width="822" alt="screen shot 2018-02-23 at 4 30 53 pm" src="https://user-images.githubusercontent.com/17734456/36617954-580be106-18b7-11e8-8ac6-c6796d04f40d.png">
<img width="1024" alt="screen shot 2018-02-23 at 4 31 36 pm" src="https://user-images.githubusercontent.com/17734456/36617956-58d47b70-18b7-11e8-8c1a-643cf7613f7e.png">

**Comment by xinyil** [comment]
https://cdhprinceton.slack.com/files/U2VJ8B3SM/F9E46BKCJ/cdhweb-proejct.mov
still experiencing some weird scroll on project page

**Comment by xinyil** [comment]
- the excerpt style is "Quote" and the color should be grey
- Project page top image shoudl be: L 9 columns, @1x W: 735 px, @2x W: 1470 px
https://docs.google.com/document/d/1v9ggePu6td5zSzEIdC2OmFkbPIoYKO8nHfjbPfu0ILA/edit#heading=h.382a2fruhan6
- excerpt and main text width are 8 column 
- seems like this page still have the "outer gutter" which has been fixed for thumbnail card page. the "outer gutter" might still be present for some other pages.
- is it possible to align credit to the top of the image?

**Comment by thatbudakguy** [comment]
corrected one font-weight thing, but otherwise this looks good.
