### ISSUE TITLE
People page - title and name spacing 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#69]
decrease the spacing
![screen shot 2017-09-27 at 1 07 06 pm](https://user-images.githubusercontent.com/17734456/30926968-e53c0306-a384-11e7-8de0-0c5481e2f001.png)

**Comment by xinyil** [comment]
<img width="966" alt="screen shot 2018-03-02 at 12 37 31 pm" src="https://user-images.githubusercontent.com/17734456/36912989-877db874-1e16-11e8-84dc-5e91f1e50a4f.png">
<img width="959" alt="screen shot 2018-03-02 at 12 36 42 pm" src="https://user-images.githubusercontent.com/17734456/36912991-878ecbdc-1e16-11e8-86a1-49857b7d8468.png">
- spacing between name and title: 5px 
- between title and image: 30px

**Comment by thatbudakguy** [comment]
This looks correct to me.
