### ISSUE TITLE
Typography - require page tile, subtile style

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#70]
- page title should be a required field 
- the heading style should only appear once

- subtle in a different style
- maybe limit the usage of H1, or whichever you defined as the heading?

<img width="1119" alt="screen shot 2017-09-27 at 1 11 14 pm" src="https://user-images.githubusercontent.com/17734456/30927230-d0f406cc-a385-11e7-9ee8-748f9a9fc0c0.png">

**Comment by thatbudakguy** [comment]
we disallow `<h1>` in rich text fields currently; edited the header styles to differentiate h1 from h2/3 more and match spec.
