### ISSUE TITLE
adding speakers to events pages without creating a profile

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/cdh-web#72]
Right now if you add a speaker to an event, you must create a profile in order for the speaker's name to appear on the website. We should be able to create a user record within the event without having to create a profile (esp. for guest speakers). If no profile is filled in, there should be a fallback logic to user name, rather than not appearing at all.

**Comment by QuakerMom** [comment]
Tested by creating new event; problem resolved.
