### ISSUE TITLE
non-CDH address display repeats information

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/cdh-web#73]
(from Mary): "When I add a location for an event that is not the CDH (e.g., East Pyne, I am required to submit a Name and an Address). If I fill out both fields, 010 East Pyne appears twice on the website. It seems like the fix would be to make the Address field not required."

**Comment by rlskoeser** [comment]
I'm keeping both name and address required, but if the address is the same as the name then it will not be displayed on the event page.

**Comment by QuakerMom** [comment]
Tested by adding new location (Joseph Henry House). Fix works.
