### ISSUE TITLE
home page doesn't display any message when there are no upcoming events

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#75]
For now, add a message with links to past events (will have to determine what event link to use, since we don't have a main event archive page).

"Next Semester's Events are being scheduled. Check back later or view past events."

**Comment by QuakerMom** [comment]
Text displays but behavior is confusing - takes 2 clicks to get to the Spring events page, middle page is currently redundant until link to past events drop down is clearer.

**Comment by rlskoeser** [comment]
I've revised this so that the most recent 6 past events are now displayed on the main events page.  @QuakerMom can you take another look and see if that works better?

**Comment by QuakerMom** [comment]
Suggested change "recent" to "past" events
