### ISSUE TITLE
events with different starting and ending months error on display

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#76]
Typo in the date rendering (should be `strftime`):
```
File "/var/www/cdh-web/cdhweb/events/models.py" in when
  153.             end_pieces.append(local_end.strfime('%B'))
```

**Comment by QuakerMom** [comment]
Card displays correctly but event detail drops second date day of month if same as first month.

**Comment by rlskoeser** [comment]
@QuakerMom I think I've corrected the display issue you found, could you take another look?

**Comment by QuakerMom** [comment]
This problem has been resolved.
