### ISSUE TITLE
Event thumbnail image display issue

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#77]
I discovered this when I uploaded a thumbnail image for my workshop:
I uploaded a PNG at 2x size 620*480 px, but the displayed thumbnail is enlarged and only parts of the image are shown.

<img width="338" alt="screen shot 2018-02-13 at 11 49 38 am" src="https://user-images.githubusercontent.com/17734456/36162307-0e68a53a-10b4-11e8-8605-de9fec5c22d0.png">

**Comment by rlskoeser** [comment]
Oh yes, this is familiar.  I think I may have a fix for that on the test site, will have to check.

**Comment by rlskoeser** [comment]
@xinyil I have the image displayed as a background and the change I've made in test is to set it be contained.  I don't think we can handle that much variation in image sizes, and after all you have documented what the images ought to be.

**Comment by thatbudakguy** [comment]
If we have the image size documented, I think we should set this to:
```css
background-position: 50% 50%;
background-size: cover;
```
and upload the correct size images. I think it's better to enforce consistency among image size and alignment than to try to handle the edge case of an image with a weird aspect ratio or with text at its edges.

**Comment by rlskoeser** [comment]
@thatbudakguy will that work for 2x images? I think I may have set it to contain to handle the 2x case (but it's been a while, I could be wrong). This sounds fine to me, you should be able to test display against events from production data.

**Comment by thatbudakguy** [comment]
we already had grid set up (on an `<a>` element, weirdly) with an image area blocked out, so this was super easy! added a div, locked it to the area, and applied the background styles to it. the MDN docs on `cover` say:
> The `cover` value specifies that the background image should be sized so that it is as small as possible while ensuring that both dimensions are greater than or equal to the corresponding size of the container.

I think that's closest to our use case.
