### ISSUE TITLE
Main nav display issue at some widths when there are several long menu items

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#79]
Look at the current Grants section to see it live.

<img width="784" alt="screen shot 2018-02-14 at 10 18 26 am" src="https://user-images.githubusercontent.com/691231/36211900-859fa2ae-1170-11e8-8513-25588e1ed11f.png">

**Comment by thatbudakguy** [comment]
Resolved with the switch to the new nav menu.
