### ISSUE TITLE
As a content editor, I want to create and edit blog posts so that I can share updates about CDH and its work.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#8]
## Notes for testing
- Blog post fields currently include a "featured image" but it isn't in the design we have, so that might change.
- We'll probably want to refine the styles and options in the wysiwyg editor but I don't know how much customization we'll have time for now.  Feel free to make notes/suggestions about how it works so we can prioritize.

**Comment by mnaydan** [comment]
Was able to create and edit three blog posts that appeared under the "updates" heading on the test site. 

Numbered and bulleted lists display in wysiwyg editor, but the numbers and bullets do not appear on the test site.
Bolding/italics works. There's no underline option available.
I was able to add an in-text image.
Table dimensions unstable in the wysiwyg editor--borders shift according to word length. But tables are not a priority, I can't imagine.

Design seems off, displaying blog title, author, and date all in a column.
<img width="332" alt="screen shot 2017-09-12 at 9 39 46 am" src="https://user-images.githubusercontent.com/22945600/30352979-448120f2-97f1-11e7-85ed-c0ac8de98620.png">
