### ISSUE TITLE
Broken image reference for events with no detail image

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#81]
Looks like the template is trying to display a detail image even if none is set.

<img width="482" alt="screen shot 2018-02-14 at 10 22 52 am" src="https://user-images.githubusercontent.com/691231/36212083-121469ae-1171-11e8-912b-d963ccfe59cd.png">

**Comment by rlskoeser** [comment]
@xinyil any design suggestions for events with no details?  It seems to be frequently the case that we have events on the site with a title and date/speaker/event type but no image or text description, which makes the page look lopsided.  Here's an example:

<img width="880" alt="screen shot 2018-02-14 at 10 25 09 am" src="https://user-images.githubusercontent.com/691231/36212212-5ecae8fe-1171-11e8-9b85-998bc13e0515.png">

**Comment by QuakerMom** [comment]
Now fixed
