### ISSUE TITLE
superuser permissions required for editing content due to mezzanine site permissions

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#82]
We discovered this a while back but never documented - content editor group permissions don't work because of mezzanine site permissions (which are enabled but we're not really using).

**Comment by rlskoeser** [comment]
I've disabled mezzanine site permissions, so we should be able to test now and see if it solves the problem.

**Comment by rlskoeser** [comment]
Tested with @QuakerMom - turned off her superuser permissions and made sure she was in content editor group.  Content editor group does _not_ have permissions on profiles / people; however, all the other permissions appear to be working properly.

I tested making a change to the Content Editor group permissions to add person and user edit permissions, but it didn't make a difference.  Possibly some interaction with using a Django proxy model for User/Permission?

**Comment by thatbudakguy** [comment]
fixed by switching to wagtail user groups
