### ISSUE TITLE
Project card - text padding

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#83]
My apologies for casing this because of my messy mockup.

Let's unite the spacing of all side to 15px:
<img width="452" alt="screen shot 2018-02-23 at 3 37 27 pm" src="https://user-images.githubusercontent.com/17734456/36615910-f17837b6-18af-11e8-8934-93abb42f2d9a.png">

current built:
<img width="833" alt="screen shot 2018-02-23 at 3 37 42 pm" src="https://user-images.githubusercontent.com/17734456/36615931-0307fc6e-18b0-11e8-83e3-a3f337db1fa7.png">

**Comment by rlskoeser** [comment]
@xinyil thanks, I remember thinking those numbers were strange.  Should I put 15px padding on the bottom also?

**Comment by xinyil** [comment]
@rlskoeser yes. I don't know how the height of the text is decided. we should probably omit part of the extra long title if it doesn't fit.

**Comment by xinyil** [comment]
add 5px for spacing between title and abstract, no sure if it should be padding or margin
<img width="1120" alt="screen shot 2018-03-02 at 12 31 21 pm" src="https://user-images.githubusercontent.com/17734456/36912765-d0b8500e-1e15-11e8-9b9b-1e9f3a8a7bb7.png">

**Comment by thatbudakguy** [comment]
Looks like this is done; I see 5px margin now. I tweaked the heading size to match the image above slightly better and give the descriptions some more breathing room.
