### ISSUE TITLE
Event individual page - info display

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#84]
- the line breaks are not great, we could break time range to a different line
- maybe could use CDH instead of Center for Digital Humanities? and put Floor B to a different line?
- Export to iCal should be link style
- too much line-height 

<img width="798" alt="screen shot 2018-02-23 at 4 59 40 pm" src="https://user-images.githubusercontent.com/17734456/36619061-70a8aa42-18bb-11e8-975e-7ab0b7d38418.png">
left: built
right: spect

**Comment by thatbudakguy** [comment]
styles for this look good. I added the speaker's institution since we have that property now; can expand to full affiliation logic later maybe.
