### ISSUE TITLE
Staff thumbnail page - alignment and spacing 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#85]
<img width="1086" alt="screen shot 2018-03-02 at 2 28 42 pm" src="https://user-images.githubusercontent.com/17734456/36918258-5166aeba-1e27-11e8-8f53-b2cb91029f56.png">

<img width="591" alt="screen shot 2018-03-02 at 2 36 42 pm" src="https://user-images.githubusercontent.com/17734456/36918262-53296d1e-1e27-11e8-81ff-210557976a9f.png">

<img width="949" alt="screen shot 2018-03-02 at 2 30 00 pm" src="https://user-images.githubusercontent.com/17734456/36918264-553a5db6-1e27-11e8-8abe-25be53ed9e89.png">

**Comment by thatbudakguy** [comment]
corrected the line height.
