### ISSUE TITLE
As a user, I want to see featured updates on the homepage so I can see what's going on at the CDH.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#89]
- [x] add most recent 3 featured blog posts to homepage view 
- [x] update homepage template to render a featured post block at the top
- [x] new block should use the post's featured image as a background, or a placeholder
- [x] new block should have pagination control for moving through the featured posts

**Comment by thatbudakguy** [comment]
@xinyil what should the smaller versions of the homepage featured content area look like?

**Comment by thatbudakguy** [comment]
The homepage "carousel" for featured posts now displays up to 6 featured posts, with the most recent first. If no featured posts are selected, it will display the 3 most recent posts. If no posts exist, it will not display.

It should cycle/fade through the posts naturally on all screen sizes except small/mobile, where it lists them vertically to be scrolled through.

**Comment by xinyil** [comment]
@thatbudakguy sorry if I wasn't clear about the image responsive behavior.
images should be centered, and constrained according to the height, and will be CUT-OFF from both sides (seeing form a 1440*900px screen won't see the whole image). 
There will be 3 sizes of images (I'll crop and supply, or give out templates so people can do themselves.), so on mobile people don't have to download a huge file.
Please see derrida site for a live demo.

Or maybe that's too difficult to handle and we need to revisit the responsive pattern？
adding @rlskoeser to weigh in.

**Comment by thatbudakguy** [comment]
Testing notes:

you can make blog posts "featured" by checking the "featured" box in the list of blog posts in the admin site and saving it.

when you look at the homepage, you should be able to see all the posts that are featured (or the most recent posts, if none are featured). see my comment above about how that should work.

**Comment by dschlein** [comment]
Featured posts show up. When more than one post is chosen, they carousel in order of most recent first, least recent last. 

Images, when added to one single post, do not show up as the background image, however.

When clicking the blue circles at the bottom to get to a particular post quicker, the page jumps up.

**Comment by dschlein** [comment]
Page still jumps when clicking the blue circles to navigate to different blog post titles.

The image added to the single post appears as a background image now. 
Featured posts carousel in chronological order, from most most recent to least recent.

**Comment by thatbudakguy** [comment]
@dschlein As the user story passes for this one as well I'm gonna close it. Added a commit that I think should resolve the "jumping" links as well, so if you wanna try it one more time, go for it (but I think it's ready regardless).
