### ISSUE TITLE
As a Content Editor, I want to designate blog posts as featured so I can highlight their importance

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#90]
- [x] add boolean field to blog post model to indicate if it's featured; default false
- [x] make field editable in the admin interface
- [x] make toggleable in list view

**Comment by thatbudakguy** [comment]
testing notes:

you can mark a blog post as featured using the checkbox that appears when viewing the list of blog posts in the admin site, or by selecting it when editing a single blog post.

**Comment by dschlein** [comment]
Tried editing on list view and individual view. Both worked. When marked as featured, it shows on the homepage.
Tried adding a background image, but the image isn't displaying.

**Comment by dschlein** [comment]
Background images added display now.
