### ISSUE TITLE
Update footer for Princeton guidelines

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#92]
- [x] Add Princeton logo
- [x] Add accessibility link

**Comment by thatbudakguy** [comment]
@rlskoeser will you take a look/"design test" this? My implementation differs slightly from the spec but I think it's a more sane/easy way to set it up and keep it responsive.

**Comment by rlskoeser** [comment]
@thatbudakguy footer looks great to me in all variants. Just needs alt text for the PU image (first thing caught by pa11y-ci! 🎉 )

**Comment by rlskoeser** [comment]
Looks good!
