### ISSUE TITLE
As a Content Editor, I should only be able to use supported formatting and tags when I edit site content so that the CDH has a uniform web presence.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#94]
- [x] remove unstyled tags from TinyMCE
- [x] auto-strip `<span>`s?
- [x] change the Image shortcut/snippet to prompt for `<figcaption>`

**Comment by rlskoeser** [comment]
Mezzanine has a setting to let override the TinyMCE config, see http://mezzanine.jupo.org/docs/configuration.html#tinymce-setup-js

TinyMCE docs for [Editor Appearance](https://www.tinymce.com/docs/configure/editor-appearance/), [Content Filtering](https://www.tinymce.com/docs/configure/content-filtering/); [image plugin](https://www.tinymce.com/docs/plugins/image/) has an `image_caption` option as of v4.3 that does exactly what we want.

**Comment by thatbudakguy** [comment]
Testing information:
you'll want to go open up something that uses the rich text editor (e.g. a blog post) in the admin part of the site, as though you were editing it (or making a new one).

- you should only be able to use styles from the dropdown menu that would normally be used to write site content (e.g. headings, paragraph style)
- you shouldn't be able to insert a table or other content using the rich text editor
- the editor should display and function normally (it appears; there's only one of it, etc)
- you should still be able to do things like insert images, which are necessary for content

**Comment by dschlein** [comment]
Styles from the dropdown menu work fine - headings, paragraphs, preformatting, etc.
There is no option to insert a table.
The editor displays normally.
When inserting the image, it doesn't show up in the editor and, therefore, doesn't show up in the edited post. The image is there in the code, but doesn't show up in the post. And the caption option doesn't appear.

**Comment by dschlein** [comment]
The image inserted shows up in the editor and in the edited post in the same size in which it was uploaded. I think the caption option appears in the code, but I'm not familiar with the correct code, so someone should take a look at that.

**Comment by thatbudakguy** [comment]
@dschlein caption option is working, so I'm gonna close this.
