### ISSUE TITLE
As a Content Editor, I want my rich text editor preview to match the way the content will display on the site so that I don't have to check the published version myself.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#95]
- [x] make TinyMCE load portions of our styles that we want

**Comment by rlskoeser** [comment]
See TinyMCE docs on [Content Appearance](https://www.tinymce.com/docs/configure/content-appearance/)

**Comment by thatbudakguy** [comment]
Testing information:
you'll want to go open up something that uses the rich text editor (e.g. a blog post) in the admin part of the site, as though you were editing it (or making a new one).

The content in the rich text editor should look exactly the way it does when it's published on the actual site. Editing the content should feel like you're editing the content as it is in the site.

**Comment by dschlein** [comment]
The edits made in the editor look the same in the editor as they do on the site. That being said, while italicizing things makes a notable difference, it's very hard to tell when something has been made bold, both in the editor and on the site.

**Comment by thatbudakguy** [comment]
@dschlein I think since the story passes on this one, we can close it. would you mind opening a separate issue for the bold text problem? there's a green "new issue" button at the top right near the issue title.

you can title it whatever you want, maybe "hard to differentiate bold text" or something. I'll follow up with you about it later, since rebecca and I can't see the problem on our machines.

**Comment by rlskoeser** [comment]
@dschlein if you're able to include a screenshot, it would be helpful - and also document what browser and version
