### ISSUE TITLE
Factor out manager/QuerySet code duplication

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#98]
limitations of Mezzanine's `DisplayableManager` have given rise to duplicating methods like `featured()`, `published()`, and `recent()` for  model `QuerySets`. We can use Django's [QuerySet.as_manager()](https://docs.djangoproject.com/en/2.0/topics/db/managers/#create-manager-with-queryset-methods) with a potential `DisplayableQuerysetMixin` to resolve this.

Affected models/managers:
- `BlogPost`
- `Event`
- `Profile`
- `Project`

**Comment by rlskoeser** [comment]
Included in #117
